//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "absLendingPurposeCodeList")
@XmlEnum
public enum AbsLendingPurposeCodeList {
    
    @XmlEnumValue("ABS-121")
    ABS_121("ABS-121"),
    
    @XmlEnumValue("ABS-123")
    ABS_123("ABS-123"),
    
    @XmlEnumValue("ABS-125")
    ABS_125("ABS-125"),
    
    @XmlEnumValue("ABS-127")
    ABS_127("ABS-127"),
    
    @XmlEnumValue("ABS-129")
    ABS_129("ABS-129"),
    
    @XmlEnumValue("ABS-131")
    ABS_131("ABS-131"),
    
    @XmlEnumValue("ABS-133")
    ABS_133("ABS-133"),
    
    @XmlEnumValue("ABS-143")
    ABS_143("ABS-143"),
    
    @XmlEnumValue("ABS-221")
    ABS_221("ABS-221"),
    
    @XmlEnumValue("ABS-223")
    ABS_223("ABS-223"),
    
    @XmlEnumValue("ABS-225")
    ABS_225("ABS-225"),
    
    @XmlEnumValue("ABS-227")
    ABS_227("ABS-227"),
    
    @XmlEnumValue("ABS-229")
    ABS_229("ABS-229"),
    
    @XmlEnumValue("ABS-231")
    ABS_231("ABS-231"),
    
    @XmlEnumValue("ABS-233")
    ABS_233("ABS-233"),
    
    @XmlEnumValue("ABS-235")
    ABS_235("ABS-235"),
    
    @XmlEnumValue("ABS-237")
    ABS_237("ABS-237"),
    
    @XmlEnumValue("ABS-239")
    ABS_239("ABS-239"),
    
    @XmlEnumValue("ABS-241")
    ABS_241("ABS-241"),
    
    @XmlEnumValue("ABS-243")
    ABS_243("ABS-243"),
    
    @XmlEnumValue("ABS-245")
    ABS_245("ABS-245"),
    
    @XmlEnumValue("ABS-247")
    ABS_247("ABS-247"),
    
    @XmlEnumValue("ABS-248")
    ABS_248("ABS-248"),
    
    @XmlEnumValue("ABS-249")
    ABS_249("ABS-249"),
    
    @XmlEnumValue("ABS-320")
    ABS_320("ABS-320"),
    
    @XmlEnumValue("ABS-321")
    ABS_321("ABS-321"),
    
    @XmlEnumValue("ABS-322")
    ABS_322("ABS-322"),
    
    @XmlEnumValue("ABS-323")
    ABS_323("ABS-323"),
    
    @XmlEnumValue("ABS-324")
    ABS_324("ABS-324"),
    
    @XmlEnumValue("ABS-326")
    ABS_326("ABS-326"),
    
    @XmlEnumValue("ABS-327")
    ABS_327("ABS-327"),
    
    @XmlEnumValue("ABS-329")
    ABS_329("ABS-329"),
    
    @XmlEnumValue("ABS-330")
    ABS_330("ABS-330"),
    
    @XmlEnumValue("ABS-331")
    ABS_331("ABS-331"),
    
    @XmlEnumValue("ABS-332")
    ABS_332("ABS-332"),
    
    @XmlEnumValue("ABS-333")
    ABS_333("ABS-333"),
    
    @XmlEnumValue("ABS-335")
    ABS_335("ABS-335"),
    
    @XmlEnumValue("ABS-336")
    ABS_336("ABS-336"),
    
    @XmlEnumValue("ABS-337")
    ABS_337("ABS-337"),
    
    @XmlEnumValue("ABS-340")
    ABS_340("ABS-340"),
    
    @XmlEnumValue("ABS-341")
    ABS_341("ABS-341"),
    
    @XmlEnumValue("ABS-342")
    ABS_342("ABS-342"),
    
    @XmlEnumValue("ABS-343")
    ABS_343("ABS-343"),
    
    @XmlEnumValue("ABS-348")
    ABS_348("ABS-348"),
    
    @XmlEnumValue("ABS-349")
    ABS_349("ABS-349");
    private final String value;
    AbsLendingPurposeCodeList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static AbsLendingPurposeCodeList fromValue(String v) {
        for (AbsLendingPurposeCodeList c: AbsLendingPurposeCodeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
