//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addressType", propOrder = {
    "deliveryPoint",
    "dxBox",
    "nonStandard",
    "poBox",
    "standard"
})
public class AddressType {
    @XmlElement(name = "DeliveryPoint")
    protected AddressType.DeliveryPoint deliveryPoint;
    @XmlElement(name = "DXBox")
    protected AddressType.DXBox dxBox;
    @XmlElement(name = "NonStandard")
    protected AddressType.NonStandard nonStandard;
    @XmlElement(name = "POBox")
    protected AddressType.POBox poBox;
    @XmlElement(name = "Standard")
    protected AddressType.Standard standard;
    @XmlAttribute(name = "AustralianPostCode")
    protected String australianPostCode;
    @XmlAttribute(name = "AustralianState")
    protected AuStateList australianState;
    @XmlAttribute(name = "City")
    protected String city;
    @XmlAttribute(name = "Country")
    protected CountryCodeList country;
    @XmlAttribute(name = "DataSource")
    protected DataSourceList dataSource;
    @XmlAttribute(name = "GNAF_ID")
    protected String gnafid;
    @XmlAttribute(name = "Latitude")
    protected BigDecimal latitude;
    @XmlAttribute(name = "LGAName")
    protected String lgaName;
    @XmlAttribute(name = "Longitude")
    protected BigDecimal longitude;
    @XmlAttribute(name = "OverseasPostCode")
    protected String overseasPostCode;
    @XmlAttribute(name = "OverseasState")
    protected String overseasState;
    @XmlAttribute(name = "Suburb")
    protected String suburb;
    @XmlAttribute(name = "TBAAddress")
    protected YesNoList tbaAddress;
    @XmlAttribute(name = "Type")
    protected AddressTypeList type;
    @XmlAttribute(name = "UniqueID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String uniqueID;
    
    public AddressType.DeliveryPoint getDeliveryPoint() {
        return deliveryPoint;
    }
    
    public void setDeliveryPoint(AddressType.DeliveryPoint value) {
        this.deliveryPoint = value;
    }
    
    public AddressType.DXBox getDXBox() {
        return dxBox;
    }
    
    public void setDXBox(AddressType.DXBox value) {
        this.dxBox = value;
    }
    
    public AddressType.NonStandard getNonStandard() {
        return nonStandard;
    }
    
    public void setNonStandard(AddressType.NonStandard value) {
        this.nonStandard = value;
    }
    
    public AddressType.POBox getPOBox() {
        return poBox;
    }
    
    public void setPOBox(AddressType.POBox value) {
        this.poBox = value;
    }
    
    public AddressType.Standard getStandard() {
        return standard;
    }
    
    public void setStandard(AddressType.Standard value) {
        this.standard = value;
    }
    
    public String getAustralianPostCode() {
        return australianPostCode;
    }
    
    public void setAustralianPostCode(String value) {
        this.australianPostCode = value;
    }
    
    public AuStateList getAustralianState() {
        return australianState;
    }
    
    public void setAustralianState(AuStateList value) {
        this.australianState = value;
    }
    
    public String getCity() {
        return city;
    }
    
    public void setCity(String value) {
        this.city = value;
    }
    
    public CountryCodeList getCountry() {
        return country;
    }
    
    public void setCountry(CountryCodeList value) {
        this.country = value;
    }
    
    public DataSourceList getDataSource() {
        return dataSource;
    }
    
    public void setDataSource(DataSourceList value) {
        this.dataSource = value;
    }
    
    public String getGNAFID() {
        return gnafid;
    }
    
    public void setGNAFID(String value) {
        this.gnafid = value;
    }
    
    public BigDecimal getLatitude() {
        return latitude;
    }
    
    public void setLatitude(BigDecimal value) {
        this.latitude = value;
    }
    
    public String getLGAName() {
        return lgaName;
    }
    
    public void setLGAName(String value) {
        this.lgaName = value;
    }
    
    public BigDecimal getLongitude() {
        return longitude;
    }
    
    public void setLongitude(BigDecimal value) {
        this.longitude = value;
    }
    
    public String getOverseasPostCode() {
        return overseasPostCode;
    }
    
    public void setOverseasPostCode(String value) {
        this.overseasPostCode = value;
    }
    
    public String getOverseasState() {
        return overseasState;
    }
    
    public void setOverseasState(String value) {
        this.overseasState = value;
    }
    
    public String getSuburb() {
        return suburb;
    }
    
    public void setSuburb(String value) {
        this.suburb = value;
    }
    
    public YesNoList getTBAAddress() {
        return tbaAddress;
    }
    
    public void setTBAAddress(YesNoList value) {
        this.tbaAddress = value;
    }
    
    public AddressTypeList getType() {
        return type;
    }
    
    public void setType(AddressTypeList value) {
        this.type = value;
    }
    
    public String getUniqueID() {
        return uniqueID;
    }
    
    public void setUniqueID(String value) {
        this.uniqueID = value;
    }
    
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class DXBox {
        @XmlAttribute(name = "Exchange")
        protected String exchange;
        @XmlAttribute(name = "Number")
        protected String number;
        @XmlAttribute(name = "Provider")
        protected String provider;
        
        public String getExchange() {
            return exchange;
        }
        
        public void setExchange(String value) {
            this.exchange = value;
        }
        
        public String getNumber() {
            return number;
        }
        
        public void setNumber(String value) {
            this.number = value;
        }
        
        public String getProvider() {
            return provider;
        }
        
        public void setProvider(String value) {
            this.provider = value;
        }
    }
    
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class DeliveryPoint {
        @XmlAttribute(name = "Identifier")
        protected String identifier;
        @XmlAttribute(name = "IdentifierBarcode")
        protected String identifierBarcode;
        
        public String getIdentifier() {
            return identifier;
        }
        
        public void setIdentifier(String value) {
            this.identifier = value;
        }
        
        public String getIdentifierBarcode() {
            return identifierBarcode;
        }
        
        public void setIdentifierBarcode(String value) {
            this.identifierBarcode = value;
        }
    }
    
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class NonStandard {
        @XmlAttribute(name = "Line1")
        protected String line1;
        @XmlAttribute(name = "Line2")
        protected String line2;
        
        public String getLine1() {
            return line1;
        }
        
        public void setLine1(String value) {
            this.line1 = value;
        }
        
        public String getLine2() {
            return line2;
        }
        
        public void setLine2(String value) {
            this.line2 = value;
        }
    }
    
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class POBox {
        @XmlAttribute(name = "Exchange")
        protected String exchange;
        @XmlAttribute(name = "Number")
        protected String number;
        @XmlAttribute(name = "Type")
        protected PoBoxTypeList type;
        
        public String getExchange() {
            return exchange;
        }
        
        public void setExchange(String value) {
            this.exchange = value;
        }
        
        public String getNumber() {
            return number;
        }
        
        public void setNumber(String value) {
            this.number = value;
        }
        
        public PoBoxTypeList getType() {
            return type;
        }
        
        public void setType(PoBoxTypeList value) {
            this.type = value;
        }
    }
    
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Standard {
        @XmlAttribute(name = "BuildingName")
        protected String buildingName;
        @XmlAttribute(name = "Level")
        protected String level;
        @XmlAttribute(name = "LevelType")
        protected LevelTypeList levelType;
        @XmlAttribute(name = "LotSection")
        protected String lotSection;
        @XmlAttribute(name = "StreetName")
        protected String streetName;
        @XmlAttribute(name = "StreetNumber")
        protected String streetNumber;
        @XmlAttribute(name = "StreetSuffix")
        protected StreetSuffixList streetSuffix;
        @XmlAttribute(name = "StreetType")
        protected StreetTypeList streetType;
        @XmlAttribute(name = "ToStreetNumber")
        protected String toStreetNumber;
        @XmlAttribute(name = "ToUnitNumber")
        protected String toUnitNumber;
        @XmlAttribute(name = "Unit")
        protected String unit;
        @XmlAttribute(name = "UnitType")
        protected UnitTypeList unitType;
        
        public String getBuildingName() {
            return buildingName;
        }
        
        public void setBuildingName(String value) {
            this.buildingName = value;
        }
        
        public String getLevel() {
            return level;
        }
        
        public void setLevel(String value) {
            this.level = value;
        }
        
        public LevelTypeList getLevelType() {
            return levelType;
        }
        
        public void setLevelType(LevelTypeList value) {
            this.levelType = value;
        }
        
        public String getLotSection() {
            return lotSection;
        }
        
        public void setLotSection(String value) {
            this.lotSection = value;
        }
        
        public String getStreetName() {
            return streetName;
        }
        
        public void setStreetName(String value) {
            this.streetName = value;
        }
        
        public String getStreetNumber() {
            return streetNumber;
        }
        
        public void setStreetNumber(String value) {
            this.streetNumber = value;
        }
        
        public StreetSuffixList getStreetSuffix() {
            return streetSuffix;
        }
        
        public void setStreetSuffix(StreetSuffixList value) {
            this.streetSuffix = value;
        }
        
        public StreetTypeList getStreetType() {
            return streetType;
        }
        
        public void setStreetType(StreetTypeList value) {
            this.streetType = value;
        }
        
        public String getToStreetNumber() {
            return toStreetNumber;
        }
        
        public void setToStreetNumber(String value) {
            this.toStreetNumber = value;
        }
        
        public String getToUnitNumber() {
            return toUnitNumber;
        }
        
        public void setToUnitNumber(String value) {
            this.toUnitNumber = value;
        }
        
        public String getUnit() {
            return unit;
        }
        
        public void setUnit(String value) {
            this.unit = value;
        }
        
        public UnitTypeList getUnitType() {
            return unitType;
        }
        
        public void setUnitType(UnitTypeList value) {
            this.unitType = value;
        }
    }
}
