//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "aggregatedTransactionsCategoryTypeList")
@XmlEnum
public enum AggregatedTransactionsCategoryTypeList {
    
    @XmlEnumValue("Alimony or Maintenance Payments")
    ALIMONY_OR_MAINTENANCE_PAYMENTS("Alimony or Maintenance Payments"),
    
    @XmlEnumValue("Ambulance Insurance")
    AMBULANCE_INSURANCE("Ambulance Insurance"),
    
    @XmlEnumValue("Animal Purchases")
    ANIMAL_PURCHASES("Animal Purchases"),
    
    @XmlEnumValue("Annuities Income")
    ANNUITIES_INCOME("Annuities Income"),
    
    @XmlEnumValue("Capital Building Costs")
    CAPITAL_BUILDING_COSTS("Capital Building Costs"),
    
    @XmlEnumValue("Child Care")
    CHILD_CARE("Child Care"),
    
    @XmlEnumValue("Child Support Payment Income")
    CHILD_SUPPORT_PAYMENT_INCOME("Child Support Payment Income"),
    
    @XmlEnumValue("Clothing and Accessories")
    CLOTHING_AND_ACCESSORIES("Clothing and Accessories"),
    
    @XmlEnumValue("Contracted Recreational Memberships and Subscriptions")
    CONTRACTED_RECREATIONAL_MEMBERSHIPS_AND_SUBSCRIPTIONS("Contracted Recreational Memberships and Subscriptions"),
    
    @XmlEnumValue("Credit Card Repayments")
    CREDIT_CARD_REPAYMENTS("Credit Card Repayments"),
    
    @XmlEnumValue("Dishonour Fees and Fines")
    DISHONOUR_FEES_AND_FINES("Dishonour Fees and Fines"),
    
    @XmlEnumValue("Dividends Income")
    DIVIDENDS_INCOME("Dividends Income"),
    
    @XmlEnumValue("Finance Repayments Excluding Mortgages and Credit Cards")
    FINANCE_REPAYMENTS_EXCLUDING_MORTGAGES_AND_CREDIT_CARDS("Finance Repayments Excluding Mortgages and Credit Cards"),
    
    @XmlEnumValue("Financial Institution Charges, Fees and Related Duties and Taxes")
    FINANCIAL_INSTITUTION_CHARGES_FEES_AND_RELATED_DUTIES_AND_TAXES("Financial Institution Charges, Fees and Related Duties and Taxes"),
    
    @XmlEnumValue("Foreign Sourced Income")
    FOREIGN_SOURCED_INCOME("Foreign Sourced Income"),
    
    @XmlEnumValue("Gambling")
    GAMBLING("Gambling"),
    
    @XmlEnumValue("Gifts and Donations")
    GIFTS_AND_DONATIONS("Gifts and Donations"),
    
    @XmlEnumValue("Government Benefits")
    GOVERNMENT_BENEFITS("Government Benefits"),
    
    @XmlEnumValue("Government Benefits - Abstudy")
    GOVERNMENT_BENEFITS_ABSTUDY("Government Benefits - Abstudy"),
    
    @XmlEnumValue("Government Benefits - Age Pension")
    GOVERNMENT_BENEFITS_AGE_PENSION("Government Benefits - Age Pension"),
    
    @XmlEnumValue("Government Benefits - Austudy")
    GOVERNMENT_BENEFITS_AUSTUDY("Government Benefits - Austudy"),
    
    @XmlEnumValue("Government Benefits - Carer Payment")
    GOVERNMENT_BENEFITS_CARER_PAYMENT("Government Benefits - Carer Payment"),
    
    @XmlEnumValue("Government Benefits - Crisis Payment")
    GOVERNMENT_BENEFITS_CRISIS_PAYMENT("Government Benefits - Crisis Payment"),
    
    @XmlEnumValue("Government Benefits - Disability Support Pension")
    GOVERNMENT_BENEFITS_DISABILITY_SUPPORT_PENSION("Government Benefits - Disability Support Pension"),
    
    @XmlEnumValue("Government Benefits - Family Allowance")
    GOVERNMENT_BENEFITS_FAMILY_ALLOWANCE("Government Benefits - Family Allowance"),
    
    @XmlEnumValue("Government Benefits - Mobility Allowance")
    GOVERNMENT_BENEFITS_MOBILITY_ALLOWANCE("Government Benefits - Mobility Allowance"),
    
    @XmlEnumValue("Government Benefits - Newstart")
    GOVERNMENT_BENEFITS_NEWSTART("Government Benefits - Newstart"),
    
    @XmlEnumValue("Government Benefits - Other")
    GOVERNMENT_BENEFITS_OTHER("Government Benefits - Other"),
    
    @XmlEnumValue("Government Benefits - Parenting Payment")
    GOVERNMENT_BENEFITS_PARENTING_PAYMENT("Government Benefits - Parenting Payment"),
    
    @XmlEnumValue("Government Benefits - Widows Allowance")
    GOVERNMENT_BENEFITS_WIDOWS_ALLOWANCE("Government Benefits - Widows Allowance"),
    
    @XmlEnumValue("Government Benefits - Youth Allowance")
    GOVERNMENT_BENEFITS_YOUTH_ALLOWANCE("Government Benefits - Youth Allowance"),
    
    @XmlEnumValue("Groceries")
    GROCERIES("Groceries"),
    
    HECS("HECS"),
    
    @XmlEnumValue("Higher Education")
    HIGHER_EDUCATION("Higher Education"),
    
    @XmlEnumValue("Holidays, Travel and Accommodation")
    HOLIDAYS_TRAVEL_AND_ACCOMMODATION("Holidays, Travel and Accommodation"),
    
    @XmlEnumValue("Hospital, Medical and Dental Insurance")
    HOSPITAL_MEDICAL_AND_DENTAL_INSURANCE("Hospital, Medical and Dental Insurance"),
    
    @XmlEnumValue("House and Contents Insurance")
    HOUSE_AND_CONTENTS_INSURANCE("House and Contents Insurance"),
    
    @XmlEnumValue("Household and Garden Furnishings and Equipment")
    HOUSEHOLD_AND_GARDEN_FURNISHINGS_AND_EQUIPMENT("Household and Garden Furnishings and Equipment"),
    
    @XmlEnumValue("Household Services")
    HOUSEHOLD_SERVICES("Household Services"),
    
    @XmlEnumValue("Income Tax")
    INCOME_TAX("Income Tax"),
    
    @XmlEnumValue("Interest Income")
    INTEREST_INCOME("Interest Income"),
    
    @XmlEnumValue("Investment Expenses")
    INVESTMENT_EXPENSES("Investment Expenses"),
    
    @XmlEnumValue("Jewellery and Watches")
    JEWELLERY_AND_WATCHES("Jewellery and Watches"),
    
    @XmlEnumValue("Life Insurance")
    LIFE_INSURANCE("Life Insurance"),
    
    @XmlEnumValue("Medical and Health")
    MEDICAL_AND_HEALTH("Medical and Health"),
    
    @XmlEnumValue("Mortgage Repayments")
    MORTGAGE_REPAYMENTS("Mortgage Repayments"),
    
    @XmlEnumValue("Net Salary")
    NET_SALARY("Net Salary"),
    
    @XmlEnumValue("Nursing Home Charges")
    NURSING_HOME_CHARGES("Nursing Home Charges"),
    
    @XmlEnumValue("Other")
    OTHER("Other"),
    
    @XmlEnumValue("Other Income")
    OTHER_INCOME("Other Income"),
    
    @XmlEnumValue("Other Insurance")
    OTHER_INSURANCE("Other Insurance"),
    
    @XmlEnumValue("Personal Care")
    PERSONAL_CARE("Personal Care"),
    
    @XmlEnumValue("Private Pension Income")
    PRIVATE_PENSION_INCOME("Private Pension Income"),
    
    @XmlEnumValue("Private Schooling Expenses")
    PRIVATE_SCHOOLING_EXPENSES("Private Schooling Expenses"),
    
    @XmlEnumValue("Professional Services, Union and Association Fees")
    PROFESSIONAL_SERVICES_UNION_AND_ASSOCIATION_FEES("Professional Services, Union and Association Fees"),
    
    @XmlEnumValue("Property Maintenance")
    PROPERTY_MAINTENANCE("Property Maintenance"),
    
    @XmlEnumValue("Public or Government Primary and Secondary Education")
    PUBLIC_OR_GOVERNMENT_PRIMARY_AND_SECONDARY_EDUCATION("Public or Government Primary and Secondary Education"),
    
    @XmlEnumValue("Purchase of Property")
    PURCHASE_OF_PROPERTY("Purchase of Property"),
    
    @XmlEnumValue("Recreation and Entertainment")
    RECREATION_AND_ENTERTAINMENT("Recreation and Entertainment"),
    
    @XmlEnumValue("Rent Payments")
    RENT_PAYMENTS("Rent Payments"),
    
    @XmlEnumValue("Rental Income")
    RENTAL_INCOME("Rental Income"),
    
    @XmlEnumValue("Sickness and Personal Accident Insurance")
    SICKNESS_AND_PERSONAL_ACCIDENT_INSURANCE("Sickness and Personal Accident Insurance"),
    
    @XmlEnumValue("Strata Fees")
    STRATA_FEES("Strata Fees"),
    
    @XmlEnumValue("Superannuation Income")
    SUPERANNUATION_INCOME("Superannuation Income"),
    
    @XmlEnumValue("Superannuation Payments")
    SUPERANNUATION_PAYMENTS("Superannuation Payments"),
    
    @XmlEnumValue("Tax and Government Fees and Payments")
    TAX_AND_GOVERNMENT_FEES_AND_PAYMENTS("Tax and Government Fees and Payments"),
    
    @XmlEnumValue("Tax Refund")
    TAX_REFUND("Tax Refund"),
    
    @XmlEnumValue("Telephone, Internet, Pay TV and Media Streaming Subscriptions")
    TELEPHONE_INTERNET_PAY_TV_AND_MEDIA_STREAMING_SUBSCRIPTIONS("Telephone, Internet, Pay TV and Media Streaming Subscriptions"),
    
    @XmlEnumValue("Transport")
    TRANSPORT("Transport"),
    
    @XmlEnumValue("Utilities")
    UTILITIES("Utilities"),
    
    @XmlEnumValue("Vehicle Insurance")
    VEHICLE_INSURANCE("Vehicle Insurance"),
    
    @XmlEnumValue("Vehicle Purchase")
    VEHICLE_PURCHASE("Vehicle Purchase"),
    
    @XmlEnumValue("Workers Compensation Income")
    WORKERS_COMPENSATION_INCOME("Workers Compensation Income");
    private final String value;
    AggregatedTransactionsCategoryTypeList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static AggregatedTransactionsCategoryTypeList fromValue(String v) {
        for (AggregatedTransactionsCategoryTypeList c: AggregatedTransactionsCategoryTypeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
