//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "agriculturalAssetTypeList")
@XmlEnum
public enum AgriculturalAssetTypeList {
    
    @XmlEnumValue("All Terrain Vehicle")
    ALL_TERRAIN_VEHICLE("All Terrain Vehicle"),
    
    @XmlEnumValue("Crops / Hay")
    CROPS_HAY("Crops / Hay"),
    
    @XmlEnumValue("Fencing")
    FENCING("Fencing"),
    
    @XmlEnumValue("Fertiliser / Slurry")
    FERTILISER_SLURRY("Fertiliser / Slurry"),
    
    @XmlEnumValue("GPS / Laser / Levelling")
    GPS_LASER_LEVELLING("GPS / Laser / Levelling"),
    
    @XmlEnumValue("Handling / Storage")
    HANDLING_STORAGE("Handling / Storage"),
    
    @XmlEnumValue("Harvester / Header")
    HARVESTER_HEADER("Harvester / Header"),
    
    @XmlEnumValue("Irrigation")
    IRRIGATION("Irrigation"),
    
    @XmlEnumValue("Livestock")
    LIVESTOCK("Livestock"),
    
    @XmlEnumValue("Other")
    OTHER("Other"),
    
    @XmlEnumValue("Seeding / Planting")
    SEEDING_PLANTING("Seeding / Planting"),
    
    @XmlEnumValue("Sprayer")
    SPRAYER("Sprayer"),
    
    @XmlEnumValue("Storage")
    STORAGE("Storage"),
    
    @XmlEnumValue("Tillage Equipment")
    TILLAGE_EQUIPMENT("Tillage Equipment"),
    
    @XmlEnumValue("Tractor - Wheeled")
    TRACTOR_WHEELED("Tractor - Wheeled"),
    
    @XmlEnumValue("Tractor Front Attachments")
    TRACTOR_FRONT_ATTACHMENTS("Tractor Front Attachments");
    private final String value;
    AgriculturalAssetTypeList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static AgriculturalAssetTypeList fromValue(String v) {
        for (AgriculturalAssetTypeList c: AgriculturalAssetTypeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
