//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "aircraftTypeList")
@XmlEnum
public enum AircraftTypeList {
    
    @XmlEnumValue("Engine")
    ENGINE("Engine"),
    
    @XmlEnumValue("Fixed Wing - Cylinder")
    FIXED_WING_CYLINDER("Fixed Wing - Cylinder"),
    
    @XmlEnumValue("Fixed Wing - Jet")
    FIXED_WING_JET("Fixed Wing - Jet"),
    
    @XmlEnumValue("Fixed Wing - Turbo Prop")
    FIXED_WING_TURBO_PROP("Fixed Wing - Turbo Prop"),
    
    @XmlEnumValue("Helicopter")
    HELICOPTER("Helicopter"),
    
    @XmlEnumValue("Other")
    OTHER("Other"),
    
    @XmlEnumValue("Ultra Light")
    ULTRA_LIGHT("Ultra Light");
    private final String value;
    AircraftTypeList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static AircraftTypeList fromValue(String v) {
        for (AircraftTypeList c: AircraftTypeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
