//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "applicationTypeList")
@XmlEnum
public enum ApplicationTypeList {
    
    @XmlEnumValue("Deposit Account")
    DEPOSIT_ACCOUNT("Deposit Account"),
    
    @XmlEnumValue("Facility Drawdown")
    FACILITY_DRAWDOWN("Facility Drawdown"),
    
    @XmlEnumValue("Lease")
    LEASE("Lease"),
    
    @XmlEnumValue("Loan")
    LOAN("Loan"),
    
    @XmlEnumValue("Loan Variation")
    LOAN_VARIATION("Loan Variation"),
    
    @XmlEnumValue("Overdraft")
    OVERDRAFT("Overdraft"),
    
    @XmlEnumValue("Prequalification")
    PREQUALIFICATION("Prequalification"),
    
    @XmlEnumValue("Unsecured")
    UNSECURED("Unsecured");
    private final String value;
    ApplicationTypeList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static ApplicationTypeList fromValue(String v) {
        for (ApplicationTypeList c: ApplicationTypeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
