//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "businessChannelTypeList")
@XmlEnum
public enum BusinessChannelTypeList {
    
    @XmlEnumValue("Bank")
    BANK("Bank"),
    
    @XmlEnumValue("Building Society")
    BUILDING_SOCIETY("Building Society"),
    
    @XmlEnumValue("Credit Union")
    CREDIT_UNION("Credit Union"),
    
    @XmlEnumValue("Mortgage Manager")
    MORTGAGE_MANAGER("Mortgage Manager"),
    
    @XmlEnumValue("Mutual Bank")
    MUTUAL_BANK("Mutual Bank"),
    
    @XmlEnumValue("Non Bank Lender")
    NON_BANK_LENDER("Non Bank Lender");
    private final String value;
    BusinessChannelTypeList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static BusinessChannelTypeList fromValue(String v) {
        for (BusinessChannelTypeList c: BusinessChannelTypeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
