//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "constructionTypeList")
@XmlEnum
public enum ConstructionTypeList {
    
    @XmlEnumValue("Full Construction")
    FULL_CONSTRUCTION("Full Construction"),
    
    @XmlEnumValue("Home Extension")
    HOME_EXTENSION("Home Extension"),
    
    @XmlEnumValue("House Land Package")
    HOUSE_LAND_PACKAGE("House Land Package"),
    
    @XmlEnumValue("Minor Non Structural Repairs")
    MINOR_NON_STRUCTURAL_REPAIRS("Minor Non Structural Repairs"),
    
    @XmlEnumValue("Renovation")
    RENOVATION("Renovation");
    private final String value;
    ConstructionTypeList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static ConstructionTypeList fromValue(String v) {
        for (ConstructionTypeList c: ConstructionTypeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
