//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "contributionFundsTypeList")
@XmlEnum
public enum ContributionFundsTypeList {
    
    @XmlEnumValue("Cash")
    CASH("Cash"),
    
    @XmlEnumValue("Deposit Paid")
    DEPOSIT_PAID("Deposit Paid"),
    
    @XmlEnumValue("Existing Equity")
    EXISTING_EQUITY("Existing Equity"),
    
    @XmlEnumValue("First Home Owner Grant")
    FIRST_HOME_OWNER_GRANT("First Home Owner Grant"),
    
    @XmlEnumValue("Genuine Savings")
    GENUINE_SAVINGS("Genuine Savings"),
    
    @XmlEnumValue("Gift")
    GIFT("Gift"),
    
    @XmlEnumValue("Inheritance")
    INHERITANCE("Inheritance"),
    
    @XmlEnumValue("Net Proceeds from Sale of Property")
    NET_PROCEEDS_FROM_SALE_OF_PROPERTY("Net Proceeds from Sale of Property"),
    
    @XmlEnumValue("Other")
    OTHER("Other"),
    
    @XmlEnumValue("Redraw")
    REDRAW("Redraw"),
    
    @XmlEnumValue("Sale of Non Real Estate Asset")
    SALE_OF_NON_REAL_ESTATE_ASSET("Sale of Non Real Estate Asset"),
    
    @XmlEnumValue("Secured VISA")
    SECURED_VISA("Secured VISA"),
    
    @XmlEnumValue("Superannuation")
    SUPERANNUATION("Superannuation"),
    
    @XmlEnumValue("Term Deposit")
    TERM_DEPOSIT("Term Deposit"),
    
    @XmlEnumValue("Unsecured Borrowing")
    UNSECURED_BORROWING("Unsecured Borrowing");
    private final String value;
    ContributionFundsTypeList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static ContributionFundsTypeList fromValue(String v) {
        for (ContributionFundsTypeList c: ContributionFundsTypeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
