//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "creditHistoryIssueList")
@XmlEnum
public enum CreditHistoryIssueList {
    
    @XmlEnumValue("Application for Hardship with Existing Lender")
    APPLICATION_FOR_HARDSHIP_WITH_EXISTING_LENDER("Application for Hardship with Existing Lender"),
    
    @XmlEnumValue("Arrears")
    ARREARS("Arrears"),
    
    @XmlEnumValue("Bankruptcy")
    BANKRUPTCY("Bankruptcy"),
    
    @XmlEnumValue("Default")
    DEFAULT("Default"),
    
    @XmlEnumValue("Financial Stress from Current Commitments")
    FINANCIAL_STRESS_FROM_CURRENT_COMMITMENTS("Financial Stress from Current Commitments"),
    
    @XmlEnumValue("Insolvency")
    INSOLVENCY("Insolvency"),
    
    @XmlEnumValue("Judgement")
    JUDGEMENT("Judgement"),
    
    @XmlEnumValue("Legal Proceeding")
    LEGAL_PROCEEDING("Legal Proceeding"),
    
    @XmlEnumValue("Other")
    OTHER("Other"),
    
    @XmlEnumValue("Scheme of Arrangement")
    SCHEME_OF_ARRANGEMENT("Scheme of Arrangement"),
    
    @XmlEnumValue("Writ")
    WRIT("Writ");
    private final String value;
    CreditHistoryIssueList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static CreditHistoryIssueList fromValue(String v) {
        for (CreditHistoryIssueList c: CreditHistoryIssueList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
