//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "currencyCodeList")
@XmlEnum
public enum CurrencyCodeList {
    
    AED,
    
    AFN,
    
    ALL,
    
    AMD,
    
    ANG,
    
    AOA,
    
    ARS,
    
    AUD,
    
    AWG,
    
    AZN,
    
    BAM,
    
    BBD,
    
    BDT,
    
    BGN,
    
    BHD,
    
    BIF,
    
    BMD,
    
    BND,
    
    BOB,
    
    BOV,
    
    BRL,
    
    BSD,
    
    BTN,
    
    BWP,
    
    BYR,
    
    BZD,
    
    CAD,
    
    CDF,
    
    CHE,
    
    CHF,
    
    CHW,
    
    CLF,
    
    CLP,
    
    CNY,
    
    COP,
    
    COU,
    
    CRC,
    
    CUC,
    
    CUP,
    
    CVE,
    
    CZK,
    
    DJF,
    
    DKK,
    
    DOP,
    
    DZD,
    
    EGP,
    
    ERN,
    
    ETB,
    
    EUR,
    
    FJD,
    
    FKP,
    
    GBP,
    
    GEL,
    
    GHS,
    
    GIP,
    
    GMD,
    
    GNF,
    
    GTQ,
    
    GYD,
    
    HKD,
    
    HNL,
    
    HRK,
    
    HTG,
    
    HUF,
    
    IDR,
    
    ILS,
    
    INR,
    
    IQD,
    
    IRR,
    
    ISK,
    
    JMD,
    
    JOD,
    
    JPY,
    
    KES,
    
    KGS,
    
    KHR,
    
    KMF,
    
    KPW,
    
    KRW,
    
    KWD,
    
    KYD,
    
    KZT,
    
    LAK,
    
    LBP,
    
    LKR,
    
    LRD,
    
    LSL,
    
    LTL,
    
    LYD,
    
    MAD,
    
    MDL,
    
    MGA,
    
    MKD,
    
    MMK,
    
    MNT,
    
    MOP,
    
    MRO,
    
    MUR,
    
    MVR,
    
    MWK,
    
    MXN,
    
    MXV,
    
    MYR,
    
    MZN,
    
    NAD,
    
    NGN,
    
    NIO,
    
    NOK,
    
    NPR,
    
    NZD,
    
    OMR,
    
    PAB,
    
    PEN,
    
    PGK,
    
    PHP,
    
    PKR,
    
    PLN,
    
    PYG,
    
    QAR,
    
    RON,
    
    RSD,
    
    RUB,
    
    RWF,
    
    SAR,
    
    SBD,
    
    SCR,
    
    SDG,
    
    SEK,
    
    SGD,
    
    SHP,
    
    SLL,
    
    SOS,
    
    SRD,
    
    SSP,
    
    STD,
    
    SVC,
    
    SYP,
    
    SZL,
    
    THB,
    
    TJS,
    
    TMT,
    
    TND,
    
    TOP,
    
    TRY,
    
    TTD,
    
    TWD,
    
    TZS,
    
    UAH,
    
    UGX,
    
    USD,
    
    USN,
    
    UYI,
    
    UYU,
    
    UZS,
    
    VEF,
    
    VND,
    
    VUV,
    
    WST,
    
    XAF,
    
    XCD,
    
    XDR,
    
    XOF,
    
    XPF,
    
    XSU,
    
    XUA,
    
    YER,
    
    ZAR,
    
    ZMW,
    
    ZWL;
    public String value() {
        return name();
    }
    public static CurrencyCodeList fromValue(String v) {
        return valueOf(v);
    }
}
