//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dealingNumberType")
public class DealingNumberType {
    @XmlAttribute(name = "AustralianState")
    protected AuStateList australianState;
    @XmlAttribute(name = "BookNumber")
    protected String bookNumber;
    @XmlAttribute(name = "RegisteredNumber")
    protected String registeredNumber;
    @XmlAttribute(name = "UniqueID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String uniqueID;
    
    public AuStateList getAustralianState() {
        return australianState;
    }
    
    public void setAustralianState(AuStateList value) {
        this.australianState = value;
    }
    
    public String getBookNumber() {
        return bookNumber;
    }
    
    public void setBookNumber(String value) {
        this.bookNumber = value;
    }
    
    public String getRegisteredNumber() {
        return registeredNumber;
    }
    
    public void setRegisteredNumber(String value) {
        this.registeredNumber = value;
    }
    
    public String getUniqueID() {
        return uniqueID;
    }
    
    public void setUniqueID(String value) {
        this.uniqueID = value;
    }
}
