//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "durationType")
public class DurationType {
    @XmlAttribute(name = "Length")
    protected BigInteger length;
    @XmlAttribute(name = "Units")
    protected DurationUnitsList units;
    
    public BigInteger getLength() {
        return length;
    }
    
    public void setLength(BigInteger value) {
        this.length = value;
    }
    
    public DurationUnitsList getUnits() {
        return units;
    }
    
    public void setUnits(DurationUnitsList value) {
        this.units = value;
    }
}
