//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "encumbranceInFavourOfCapacityList")
@XmlEnum
public enum EncumbranceInFavourOfCapacityList {
    
    @XmlEnumValue("Asset Held in Own Right and on Behalf of Trust")
    ASSET_HELD_IN_OWN_RIGHT_AND_ON_BEHALF_OF_TRUST("Asset Held in Own Right and on Behalf of Trust"),
    
    @XmlEnumValue("Limited to Particular Property or Asset")
    LIMITED_TO_PARTICULAR_PROPERTY_OR_ASSET("Limited to Particular Property or Asset"),
    
    @XmlEnumValue("Own Right Only")
    OWN_RIGHT_ONLY("Own Right Only"),
    
    @XmlEnumValue("Partnership")
    PARTNERSHIP("Partnership"),
    
    @XmlEnumValue("Trust Assets Only")
    TRUST_ASSETS_ONLY("Trust Assets Only");
    private final String value;
    EncumbranceInFavourOfCapacityList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static EncumbranceInFavourOfCapacityList fromValue(String v) {
        for (EncumbranceInFavourOfCapacityList c: EncumbranceInFavourOfCapacityList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
