//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "estimateBasisRealEstateAssetList")
@XmlEnum
public enum EstimateBasisRealEstateAssetList {
    
    @XmlEnumValue("Applicant Estimate")
    APPLICANT_ESTIMATE("Applicant Estimate"),
    
    @XmlEnumValue("Bank Assessment")
    BANK_ASSESSMENT("Bank Assessment"),
    
    @XmlEnumValue("Certified Valuation")
    CERTIFIED_VALUATION("Certified Valuation"),
    
    @XmlEnumValue("Electronic Valuation")
    ELECTRONIC_VALUATION("Electronic Valuation"),
    
    @XmlEnumValue("Rates Notice")
    RATES_NOTICE("Rates Notice"),
    
    @XmlEnumValue("RP Data")
    RP_DATA("RP Data");
    private final String value;
    EstimateBasisRealEstateAssetList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static EstimateBasisRealEstateAssetList fromValue(String v) {
        for (EstimateBasisRealEstateAssetList c: EstimateBasisRealEstateAssetList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
