//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "eventNameApplicationInstructionsList")
@XmlEnum
public enum EventNameApplicationInstructionsList {
    
    @XmlEnumValue("Additional Information Has Been Requested")
    ADDITIONAL_INFORMATION_HAS_BEEN_REQUESTED("Additional Information Has Been Requested"),
    
    @XmlEnumValue("Application Received")
    APPLICATION_RECEIVED("Application Received"),
    
    @XmlEnumValue("Application Registered")
    APPLICATION_REGISTERED("Application Registered"),
    
    @XmlEnumValue("Application Sent")
    APPLICATION_SENT("Application Sent"),
    
    @XmlEnumValue("Awaiting Supporting Documents")
    AWAITING_SUPPORTING_DOCUMENTS("Awaiting Supporting Documents"),
    
    @XmlEnumValue("Cancelled")
    CANCELLED("Cancelled"),
    
    @XmlEnumValue("Comment")
    COMMENT("Comment"),
    
    @XmlEnumValue("Commission Paid")
    COMMISSION_PAID("Commission Paid"),
    
    @XmlEnumValue("Conditionally Approved")
    CONDITIONALLY_APPROVED("Conditionally Approved"),
    
    @XmlEnumValue("Credit Check Ordered")
    CREDIT_CHECK_ORDERED("Credit Check Ordered"),
    
    @XmlEnumValue("Credit Check Received")
    CREDIT_CHECK_RECEIVED("Credit Check Received"),
    
    @XmlEnumValue("Declined")
    DECLINED("Declined"),
    
    @XmlEnumValue("Discharged")
    DISCHARGED("Discharged"),
    
    @XmlEnumValue("Duplicate Submission")
    DUPLICATE_SUBMISSION("Duplicate Submission"),
    
    @XmlEnumValue("Employment Check Commenced")
    EMPLOYMENT_CHECK_COMMENCED("Employment Check Commenced"),
    
    @XmlEnumValue("Employment Check Completed")
    EMPLOYMENT_CHECK_COMPLETED("Employment Check Completed"),
    
    @XmlEnumValue("Employment Check Delayed")
    EMPLOYMENT_CHECK_DELAYED("Employment Check Delayed"),
    
    @XmlEnumValue("Error on Submission")
    ERROR_ON_SUBMISSION("Error on Submission"),
    
    @XmlEnumValue("LMI Ordered")
    LMI_ORDERED("LMI Ordered"),
    
    @XmlEnumValue("LMI Response Received")
    LMI_RESPONSE_RECEIVED("LMI Response Received"),
    
    @XmlEnumValue("Loan Documents and Requirements Complete")
    LOAN_DOCUMENTS_AND_REQUIREMENTS_COMPLETE("Loan Documents and Requirements Complete"),
    
    @XmlEnumValue("Loan Documents and Requirements Incomplete")
    LOAN_DOCUMENTS_AND_REQUIREMENTS_INCOMPLETE("Loan Documents and Requirements Incomplete"),
    
    @XmlEnumValue("Loan Documents Certified for Settlement")
    LOAN_DOCUMENTS_CERTIFIED_FOR_SETTLEMENT("Loan Documents Certified for Settlement"),
    
    @XmlEnumValue("Loan Documents Error Message Returned")
    LOAN_DOCUMENTS_ERROR_MESSAGE_RETURNED("Loan Documents Error Message Returned"),
    
    @XmlEnumValue("Loan Documents Follow Up")
    LOAN_DOCUMENTS_FOLLOW_UP("Loan Documents Follow Up"),
    
    @XmlEnumValue("Loan Documents Issued")
    LOAN_DOCUMENTS_ISSUED("Loan Documents Issued"),
    
    @XmlEnumValue("Loan Documents Preparation Commenced")
    LOAN_DOCUMENTS_PREPARATION_COMMENCED("Loan Documents Preparation Commenced"),
    
    @XmlEnumValue("Loan Documents Produced")
    LOAN_DOCUMENTS_PRODUCED("Loan Documents Produced"),
    
    @XmlEnumValue("Loan Documents Produced and Returned to Lender")
    LOAN_DOCUMENTS_PRODUCED_AND_RETURNED_TO_LENDER("Loan Documents Produced and Returned to Lender"),
    
    @XmlEnumValue("Loan Documents Re-issue Request Sent")
    LOAN_DOCUMENTS_RE_ISSUE_REQUEST_SENT("Loan Documents Re-issue Request Sent"),
    
    @XmlEnumValue("Loan Documents Re-Issued")
    LOAN_DOCUMENTS_RE_ISSUED("Loan Documents Re-Issued"),
    
    @XmlEnumValue("Loan Documents Received")
    LOAN_DOCUMENTS_RECEIVED("Loan Documents Received"),
    
    @XmlEnumValue("Loan Documents Request Received")
    LOAN_DOCUMENTS_REQUEST_RECEIVED("Loan Documents Request Received"),
    
    @XmlEnumValue("Loan Documents Request Sent")
    LOAN_DOCUMENTS_REQUEST_SENT("Loan Documents Request Sent"),
    
    @XmlEnumValue("Loan Documents Returned Enquiry")
    LOAN_DOCUMENTS_RETURNED_ENQUIRY("Loan Documents Returned Enquiry"),
    
    @XmlEnumValue("Loan Funded by Lender")
    LOAN_FUNDED_BY_LENDER("Loan Funded by Lender"),
    
    @XmlEnumValue("Payout Figure Received")
    PAYOUT_FIGURE_RECEIVED("Payout Figure Received"),
    
    @XmlEnumValue("Payout Figure Rejected")
    PAYOUT_FIGURE_REJECTED("Payout Figure Rejected"),
    
    @XmlEnumValue("PreApproved")
    PRE_APPROVED("PreApproved"),
    
    @XmlEnumValue("Progress Payment Complete")
    PROGRESS_PAYMENT_COMPLETE("Progress Payment Complete"),
    
    @XmlEnumValue("Progress Payment Message")
    PROGRESS_PAYMENT_MESSAGE("Progress Payment Message"),
    
    @XmlEnumValue("Ready for Progress Payment")
    READY_FOR_PROGRESS_PAYMENT("Ready for Progress Payment"),
    
    @XmlEnumValue("Ready for Settlement")
    READY_FOR_SETTLEMENT("Ready for Settlement"),
    
    @XmlEnumValue("Referred for Credit Assessment")
    REFERRED_FOR_CREDIT_ASSESSMENT("Referred for Credit Assessment"),
    
    @XmlEnumValue("Referred to Broker")
    REFERRED_TO_BROKER("Referred to Broker"),
    
    @XmlEnumValue("Referred to Mortgage Insurer")
    REFERRED_TO_MORTGAGE_INSURER("Referred to Mortgage Insurer"),
    
    @XmlEnumValue("Security Documents Sent to Custodian")
    SECURITY_DOCUMENTS_SENT_TO_CUSTODIAN("Security Documents Sent to Custodian"),
    
    @XmlEnumValue("Security Documents Sent to Lender")
    SECURITY_DOCUMENTS_SENT_TO_LENDER("Security Documents Sent to Lender"),
    
    @XmlEnumValue("Security Packet Received")
    SECURITY_PACKET_RECEIVED("Security Packet Received"),
    
    @XmlEnumValue("Security Registered")
    SECURITY_REGISTERED("Security Registered"),
    
    @XmlEnumValue("Service Coordinator Assigned")
    SERVICE_COORDINATOR_ASSIGNED("Service Coordinator Assigned"),
    
    @XmlEnumValue("Settlement Cancelled")
    SETTLEMENT_CANCELLED("Settlement Cancelled"),
    
    @XmlEnumValue("Settlement Completed")
    SETTLEMENT_COMPLETED("Settlement Completed"),
    
    @XmlEnumValue("Settlement Date Booked")
    SETTLEMENT_DATE_BOOKED("Settlement Date Booked"),
    
    @XmlEnumValue("Settlement Date Confirmed")
    SETTLEMENT_DATE_CONFIRMED("Settlement Date Confirmed"),
    
    @XmlEnumValue("Settlement Date Estimated")
    SETTLEMENT_DATE_ESTIMATED("Settlement Date Estimated"),
    
    @XmlEnumValue("Settlement Delayed")
    SETTLEMENT_DELAYED("Settlement Delayed"),
    
    @XmlEnumValue("Settlement Funds Received")
    SETTLEMENT_FUNDS_RECEIVED("Settlement Funds Received"),
    
    @XmlEnumValue("Settlement Rebooked")
    SETTLEMENT_REBOOKED("Settlement Rebooked"),
    
    @XmlEnumValue("Solicitor Instructed")
    SOLICITOR_INSTRUCTED("Solicitor Instructed"),
    
    @XmlEnumValue("Solicitor Instruction Received")
    SOLICITOR_INSTRUCTION_RECEIVED("Solicitor Instruction Received"),
    
    @XmlEnumValue("Supporting Documents Determined to Be Incomplete")
    SUPPORTING_DOCUMENTS_DETERMINED_TO_BE_INCOMPLETE("Supporting Documents Determined to Be Incomplete"),
    
    @XmlEnumValue("Supporting Documents Have Been Verified")
    SUPPORTING_DOCUMENTS_HAVE_BEEN_VERIFIED("Supporting Documents Have Been Verified"),
    
    @XmlEnumValue("Supporting Documents Received")
    SUPPORTING_DOCUMENTS_RECEIVED("Supporting Documents Received"),
    
    @XmlEnumValue("Title Search Ordered")
    TITLE_SEARCH_ORDERED("Title Search Ordered"),
    
    @XmlEnumValue("Title Search Received")
    TITLE_SEARCH_RECEIVED("Title Search Received"),
    
    @XmlEnumValue("Unconditionally Approved")
    UNCONDITIONALLY_APPROVED("Unconditionally Approved"),
    
    @XmlEnumValue("Valuation Approved")
    VALUATION_APPROVED("Valuation Approved"),
    
    @XmlEnumValue("Valuation Cancelled")
    VALUATION_CANCELLED("Valuation Cancelled"),
    
    @XmlEnumValue("Valuation Not Required")
    VALUATION_NOT_REQUIRED("Valuation Not Required"),
    
    @XmlEnumValue("Valuation Ordered")
    VALUATION_ORDERED("Valuation Ordered"),
    
    @XmlEnumValue("Valuation Received")
    VALUATION_RECEIVED("Valuation Received"),
    
    @XmlEnumValue("Variation Initialised")
    VARIATION_INITIALISED("Variation Initialised"),
    
    @XmlEnumValue("Withdrawn")
    WITHDRAWN("Withdrawn");
    private final String value;
    EventNameApplicationInstructionsList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static EventNameApplicationInstructionsList fromValue(String v) {
        for (EventNameApplicationInstructionsList c: EventNameApplicationInstructionsList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
