//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "feeTypeList")
@XmlEnum
public enum FeeTypeList {
    
    @XmlEnumValue("Acceptance Fee")
    ACCEPTANCE_FEE("Acceptance Fee"),
    
    @XmlEnumValue("Additional Security Fee")
    ADDITIONAL_SECURITY_FEE("Additional Security Fee"),
    
    @XmlEnumValue("Annual Fee")
    ANNUAL_FEE("Annual Fee"),
    
    @XmlEnumValue("Application Fee")
    APPLICATION_FEE("Application Fee"),
    
    @XmlEnumValue("Brokerage Fee")
    BROKERAGE_FEE("Brokerage Fee"),
    
    @XmlEnumValue("Cash Benefit Insurance")
    CASH_BENEFIT_INSURANCE("Cash Benefit Insurance"),
    
    @XmlEnumValue("Construction Progress Inspection Fee")
    CONSTRUCTION_PROGRESS_INSPECTION_FEE("Construction Progress Inspection Fee"),
    
    @XmlEnumValue("Consumer Credit Insurance")
    CONSUMER_CREDIT_INSURANCE("Consumer Credit Insurance"),
    
    @XmlEnumValue("Documentation Fee")
    DOCUMENTATION_FEE("Documentation Fee"),
    
    @XmlEnumValue("Early Repayment Admin Fee")
    EARLY_REPAYMENT_ADMIN_FEE("Early Repayment Admin Fee"),
    
    @XmlEnumValue("Establishment Fee")
    ESTABLISHMENT_FEE("Establishment Fee"),
    
    @XmlEnumValue("Extended Warranty Insurance")
    EXTENDED_WARRANTY_INSURANCE("Extended Warranty Insurance"),
    
    @XmlEnumValue("Guarantee Asset Protection Insurance")
    GUARANTEE_ASSET_PROTECTION_INSURANCE("Guarantee Asset Protection Insurance"),
    
    @XmlEnumValue("Land Titles Office Final Search Fee")
    LAND_TITLES_OFFICE_FINAL_SEARCH_FEE("Land Titles Office Final Search Fee"),
    
    @XmlEnumValue("Land Titles Office Search Fee")
    LAND_TITLES_OFFICE_SEARCH_FEE("Land Titles Office Search Fee"),
    
    @XmlEnumValue("Legal Fee")
    LEGAL_FEE("Legal Fee"),
    
    LMI("LMI"),
    
    @XmlEnumValue("Loan Fee")
    LOAN_FEE("Loan Fee"),
    
    @XmlEnumValue("Mortgage Registration")
    MORTGAGE_REGISTRATION("Mortgage Registration"),
    
    @XmlEnumValue("Motor Vehicle Insurance")
    MOTOR_VEHICLE_INSURANCE("Motor Vehicle Insurance"),
    
    @XmlEnumValue("Other")
    OTHER("Other"),
    
    @XmlEnumValue("Package Fee")
    PACKAGE_FEE("Package Fee"),
    
    @XmlEnumValue("Rate Lock Fee")
    RATE_LOCK_FEE("Rate Lock Fee"),
    
    @XmlEnumValue("Re-documentation Fee")
    RE_DOCUMENTATION_FEE("Re-documentation Fee"),
    
    @XmlEnumValue("Reduced Equity Fee")
    REDUCED_EQUITY_FEE("Reduced Equity Fee"),
    
    @XmlEnumValue("Risk Fee")
    RISK_FEE("Risk Fee"),
    
    @XmlEnumValue("Rollover Fee")
    ROLLOVER_FEE("Rollover Fee"),
    
    @XmlEnumValue("Security Guarantee Fee")
    SECURITY_GUARANTEE_FEE("Security Guarantee Fee"),
    
    @XmlEnumValue("Security Release Fee")
    SECURITY_RELEASE_FEE("Security Release Fee"),
    
    @XmlEnumValue("Service Plan")
    SERVICE_PLAN("Service Plan"),
    
    @XmlEnumValue("Settlement Fee")
    SETTLEMENT_FEE("Settlement Fee"),
    
    @XmlEnumValue("Stamp Duty on Mortgage")
    STAMP_DUTY_ON_MORTGAGE("Stamp Duty on Mortgage"),
    
    @XmlEnumValue("Stamp Duty on Transfer of Property")
    STAMP_DUTY_ON_TRANSFER_OF_PROPERTY("Stamp Duty on Transfer of Property"),
    
    @XmlEnumValue("Substitute Security Fee")
    SUBSTITUTE_SECURITY_FEE("Substitute Security Fee"),
    
    @XmlEnumValue("Switch Fee")
    SWITCH_FEE("Switch Fee"),
    
    @XmlEnumValue("Third Party Document Production Fee")
    THIRD_PARTY_DOCUMENT_PRODUCTION_FEE("Third Party Document Production Fee"),
    
    @XmlEnumValue("Title Transfer Fee")
    TITLE_TRANSFER_FEE("Title Transfer Fee"),
    
    @XmlEnumValue("Tyre and Rim Insurance")
    TYRE_AND_RIM_INSURANCE("Tyre and Rim Insurance"),
    
    @XmlEnumValue("Unused Facility Fee")
    UNUSED_FACILITY_FEE("Unused Facility Fee"),
    
    @XmlEnumValue("Valuation Fee")
    VALUATION_FEE("Valuation Fee"),
    
    @XmlEnumValue("Withdrawal of Caveat Fee")
    WITHDRAWAL_OF_CAVEAT_FEE("Withdrawal of Caveat Fee"),
    
    @XmlEnumValue("Withdrawal of Writ Fee")
    WITHDRAWAL_OF_WRIT_FEE("Withdrawal of Writ Fee");
    private final String value;
    FeeTypeList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static FeeTypeList fromValue(String v) {
        for (FeeTypeList c: FeeTypeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
