//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "financialAssetTypeList")
@XmlEnum
public enum FinancialAssetTypeList {
    
    @XmlEnumValue("Cash")
    CASH("Cash"),
    
    @XmlEnumValue("Investment")
    INVESTMENT("Investment"),
    
    @XmlEnumValue("Managed Funds")
    MANAGED_FUNDS("Managed Funds"),
    
    @XmlEnumValue("Other")
    OTHER("Other"),
    
    @XmlEnumValue("Pension Account")
    PENSION_ACCOUNT("Pension Account"),
    
    @XmlEnumValue("Receivables")
    RECEIVABLES("Receivables"),
    
    @XmlEnumValue("Savings Account")
    SAVINGS_ACCOUNT("Savings Account"),
    
    @XmlEnumValue("Shares and Debentures")
    SHARES_AND_DEBENTURES("Shares and Debentures"),
    
    @XmlEnumValue("Superannuation")
    SUPERANNUATION("Superannuation"),
    
    @XmlEnumValue("Term Deposit")
    TERM_DEPOSIT("Term Deposit"),
    
    @XmlEnumValue("Transaction Account")
    TRANSACTION_ACCOUNT("Transaction Account");
    private final String value;
    FinancialAssetTypeList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static FinancialAssetTypeList fromValue(String v) {
        for (FinancialAssetTypeList c: FinancialAssetTypeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
