//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "funderList")
@XmlEnum
public enum FunderList {
    
    @XmlEnumValue("Adelaide Bank")
    ADELAIDE_BANK("Adelaide Bank"),
    
    @XmlEnumValue("Advantedge")
    ADVANTEDGE("Advantedge"),
    
    @XmlEnumValue("BC Securities")
    BC_SECURITIES("BC Securities"),
    
    @XmlEnumValue("Bendigo Bank")
    BENDIGO_BANK("Bendigo Bank"),
    
    @XmlEnumValue("Firstmac")
    FIRSTMAC("Firstmac"),
    
    @XmlEnumValue("LaTrobe")
    LA_TROBE("LaTrobe"),
    
    @XmlEnumValue("Macquarie")
    MACQUARIE("Macquarie"),
    
    @XmlEnumValue("Origin")
    ORIGIN("Origin"),
    
    @XmlEnumValue("Pepper")
    PEPPER("Pepper"),
    
    @XmlEnumValue("RedZed")
    RED_ZED("RedZed"),
    
    @XmlEnumValue("Resimac")
    RESIMAC("Resimac"),
    
    @XmlEnumValue("Sintex")
    SINTEX("Sintex");
    private final String value;
    FunderList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static FunderList fromValue(String v) {
        for (FunderList c: FunderList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
