//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "fundsAccessTypeList")
@XmlEnum
public enum FundsAccessTypeList {
    
    @XmlEnumValue("Line of Credit")
    LINE_OF_CREDIT("Line of Credit"),
    
    @XmlEnumValue("None")
    NONE("None"),
    
    @XmlEnumValue("Offset")
    OFFSET("Offset"),
    
    @XmlEnumValue("Redraw")
    REDRAW("Redraw");
    private final String value;
    FundsAccessTypeList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static FundsAccessTypeList fromValue(String v) {
        for (FundsAccessTypeList c: FundsAccessTypeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
