//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "goodToBeUsedLocationList")
@XmlEnum
public enum GoodToBeUsedLocationList {
    
    @XmlEnumValue("On Business Premises")
    ON_BUSINESS_PREMISES("On Business Premises"),
    
    @XmlEnumValue("On Site")
    ON_SITE("On Site"),
    
    @XmlEnumValue("On Site Daily Return")
    ON_SITE_DAILY_RETURN("On Site Daily Return");
    private final String value;
    GoodToBeUsedLocationList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static GoodToBeUsedLocationList fromValue(String v) {
        for (GoodToBeUsedLocationList c: GoodToBeUsedLocationList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
