//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "goodsDeliveryList")
@XmlEnum
public enum GoodsDeliveryList {
    
    @XmlEnumValue("Already Delivered")
    ALREADY_DELIVERED("Already Delivered"),
    
    @XmlEnumValue("To Be Delivered on Payment")
    TO_BE_DELIVERED_ON_PAYMENT("To Be Delivered on Payment"),
    
    @XmlEnumValue("Will Be Delivered on Date")
    WILL_BE_DELIVERED_ON_DATE("Will Be Delivered on Date");
    private final String value;
    GoodsDeliveryList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static GoodsDeliveryList fromValue(String v) {
        for (GoodsDeliveryList c: GoodsDeliveryList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
