//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "governmentBenefitsTypeList")
@XmlEnum
public enum GovernmentBenefitsTypeList {
    
    @XmlEnumValue("Abstudy")
    ABSTUDY("Abstudy"),
    
    @XmlEnumValue("Age Pension")
    AGE_PENSION("Age Pension"),
    
    @XmlEnumValue("Austudy")
    AUSTUDY("Austudy"),
    
    @XmlEnumValue("Carer Payment")
    CARER_PAYMENT("Carer Payment"),
    
    @XmlEnumValue("Child Support")
    CHILD_SUPPORT("Child Support"),
    
    @XmlEnumValue("Crisis Payment")
    CRISIS_PAYMENT("Crisis Payment"),
    
    @XmlEnumValue("Disability Support Pension")
    DISABILITY_SUPPORT_PENSION("Disability Support Pension"),
    
    @XmlEnumValue("Family Allowance")
    FAMILY_ALLOWANCE("Family Allowance"),
    
    @XmlEnumValue("Mobility Allowance")
    MOBILITY_ALLOWANCE("Mobility Allowance"),
    
    @XmlEnumValue("Other")
    OTHER("Other"),
    
    @XmlEnumValue("Parenting Payment")
    PARENTING_PAYMENT("Parenting Payment"),
    
    @XmlEnumValue("Widows Allowance")
    WIDOWS_ALLOWANCE("Widows Allowance"),
    
    @XmlEnumValue("Youth Allowance")
    YOUTH_ALLOWANCE("Youth Allowance");
    private final String value;
    GovernmentBenefitsTypeList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static GovernmentBenefitsTypeList fromValue(String v) {
        for (GovernmentBenefitsTypeList c: GovernmentBenefitsTypeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
