//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "guarantorAccessList")
@XmlEnum
public enum GuarantorAccessList {
    
    @XmlEnumValue("Full Access")
    FULL_ACCESS("Full Access"),
    
    @XmlEnumValue("Information Only Access")
    INFORMATION_ONLY_ACCESS("Information Only Access"),
    
    @XmlEnumValue("No Access")
    NO_ACCESS("No Access"),
    
    @XmlEnumValue("Transacting Access")
    TRANSACTING_ACCESS("Transacting Access");
    private final String value;
    GuarantorAccessList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static GuarantorAccessList fromValue(String v) {
        for (GuarantorAccessList c: GuarantorAccessList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
