//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "independentAdviceTypeRequiredList")
@XmlEnum
public enum IndependentAdviceTypeRequiredList {
    
    @XmlEnumValue("Financial Advice")
    FINANCIAL_ADVICE("Financial Advice"),
    
    @XmlEnumValue("Financial and Legal Advice")
    FINANCIAL_AND_LEGAL_ADVICE("Financial and Legal Advice"),
    
    @XmlEnumValue("Legal Advice")
    LEGAL_ADVICE("Legal Advice");
    private final String value;
    IndependentAdviceTypeRequiredList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static IndependentAdviceTypeRequiredList fromValue(String v) {
        for (IndependentAdviceTypeRequiredList c: IndependentAdviceTypeRequiredList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
