//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "interestOnlyReasonList")
@XmlEnum
public enum InterestOnlyReasonList {
    
    @XmlEnumValue("Create funds for investment purposes")
    CREATE_FUNDS_FOR_INVESTMENT_PURPOSES("Create funds for investment purposes"),
    
    @XmlEnumValue("Large non-recurring expenses")
    LARGE_NON_RECURRING_EXPENSES("Large non-recurring expenses"),
    
    @XmlEnumValue("Maximise cash flow")
    MAXIMISE_CASH_FLOW("Maximise cash flow"),
    
    @XmlEnumValue("Minimise Cash Flow Impact During Construction")
    MINIMISE_CASH_FLOW_IMPACT_DURING_CONSTRUCTION("Minimise Cash Flow Impact During Construction"),
    
    @XmlEnumValue("Minimise Cash Flow Impact During the Bridging Period")
    MINIMISE_CASH_FLOW_IMPACT_DURING_THE_BRIDGING_PERIOD("Minimise Cash Flow Impact During the Bridging Period"),
    
    @XmlEnumValue("Other reason")
    OTHER_REASON("Other reason"),
    
    @XmlEnumValue("Plan to convert to investment property")
    PLAN_TO_CONVERT_TO_INVESTMENT_PROPERTY("Plan to convert to investment property"),
    
    @XmlEnumValue("Principal reductions in an offset facility")
    PRINCIPAL_REDUCTIONS_IN_AN_OFFSET_FACILITY("Principal reductions in an offset facility"),
    
    @XmlEnumValue("Recommendation From Independent Financial Adviser")
    RECOMMENDATION_FROM_INDEPENDENT_FINANCIAL_ADVISER("Recommendation From Independent Financial Adviser"),
    
    @XmlEnumValue("Taxation, financial or accounting reasons")
    TAXATION_FINANCIAL_OR_ACCOUNTING_REASONS("Taxation, financial or accounting reasons"),
    
    @XmlEnumValue("Temporary reduction in income")
    TEMPORARY_REDUCTION_IN_INCOME("Temporary reduction in income"),
    
    @XmlEnumValue("Variable income")
    VARIABLE_INCOME("Variable income");
    private final String value;
    InterestOnlyReasonList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static InterestOnlyReasonList fromValue(String v) {
        for (InterestOnlyReasonList c: InterestOnlyReasonList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
