//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "interestChargeFrequencyList")
@XmlEnum
public enum InterestChargeFrequencyList {
    
    @XmlEnumValue("Daily")
    DAILY("Daily"),
    
    @XmlEnumValue("Every Two Months")
    EVERY_TWO_MONTHS("Every Two Months"),
    
    @XmlEnumValue("Fortnightly")
    FORTNIGHTLY("Fortnightly"),
    
    @XmlEnumValue("Half Yearly")
    HALF_YEARLY("Half Yearly"),
    
    @XmlEnumValue("Monthly")
    MONTHLY("Monthly"),
    
    @XmlEnumValue("Quarterly")
    QUARTERLY("Quarterly"),
    
    @XmlEnumValue("Weekly")
    WEEKLY("Weekly"),
    
    @XmlEnumValue("Yearly")
    YEARLY("Yearly");
    private final String value;
    InterestChargeFrequencyList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static InterestChargeFrequencyList fromValue(String v) {
        for (InterestChargeFrequencyList c: InterestChargeFrequencyList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
