//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "kinRelationshipList")
@XmlEnum
public enum KinRelationshipList {
    
    @XmlEnumValue("Child")
    CHILD("Child"),
    
    @XmlEnumValue("Friend")
    FRIEND("Friend"),
    
    @XmlEnumValue("Grandparent")
    GRANDPARENT("Grandparent"),
    
    @XmlEnumValue("Other Relative")
    OTHER_RELATIVE("Other Relative"),
    
    @XmlEnumValue("Parent")
    PARENT("Parent"),
    
    @XmlEnumValue("Sibling")
    SIBLING("Sibling"),
    
    @XmlEnumValue("Spouse")
    SPOUSE("Spouse");
    private final String value;
    KinRelationshipList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static KinRelationshipList fromValue(String v) {
        for (KinRelationshipList c: KinRelationshipList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
