//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "landValueEstimateBasisList")
@XmlEnum
public enum LandValueEstimateBasisList {
    
    @XmlEnumValue("Estimated Market Value")
    ESTIMATED_MARKET_VALUE("Estimated Market Value"),
    
    @XmlEnumValue("Purchase Price")
    PURCHASE_PRICE("Purchase Price");
    private final String value;
    LandValueEstimateBasisList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static LandValueEstimateBasisList fromValue(String v) {
        for (LandValueEstimateBasisList c: LandValueEstimateBasisList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
