//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "levelTypeList")
@XmlEnum
public enum LevelTypeList {
    
    @XmlEnumValue("Basement")
    BASEMENT("Basement"),
    
    @XmlEnumValue("Floor")
    FLOOR("Floor"),
    
    @XmlEnumValue("Ground")
    GROUND("Ground"),
    
    @XmlEnumValue("Level")
    LEVEL("Level"),
    
    @XmlEnumValue("Lower Ground Floor")
    LOWER_GROUND_FLOOR("Lower Ground Floor"),
    
    @XmlEnumValue("Lower Level")
    LOWER_LEVEL("Lower Level"),
    
    @XmlEnumValue("Mezzanine")
    MEZZANINE("Mezzanine"),
    
    @XmlEnumValue("Observation Deck")
    OBSERVATION_DECK("Observation Deck"),
    
    @XmlEnumValue("Parking")
    PARKING("Parking"),
    
    @XmlEnumValue("Penthouse")
    PENTHOUSE("Penthouse"),
    
    @XmlEnumValue("Platform")
    PLATFORM("Platform"),
    
    @XmlEnumValue("Podium")
    PODIUM("Podium"),
    
    @XmlEnumValue("Rooftop")
    ROOFTOP("Rooftop"),
    
    @XmlEnumValue("Sub-basement")
    SUB_BASEMENT("Sub-basement"),
    
    @XmlEnumValue("Upper Ground Floor")
    UPPER_GROUND_FLOOR("Upper Ground Floor");
    private final String value;
    LevelTypeList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static LevelTypeList fromValue(String v) {
        for (LevelTypeList c: LevelTypeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
