//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "liabilityTypeList")
@XmlEnum
public enum LiabilityTypeList {
    
    @XmlEnumValue("Bridging Finance")
    BRIDGING_FINANCE("Bridging Finance"),
    
    @XmlEnumValue("Car Loan")
    CAR_LOAN("Car Loan"),
    
    @XmlEnumValue("Commercial Bill")
    COMMERCIAL_BILL("Commercial Bill"),
    
    @XmlEnumValue("Contingent Liability")
    CONTINGENT_LIABILITY("Contingent Liability"),
    
    @XmlEnumValue("Credit Card")
    CREDIT_CARD("Credit Card"),
    
    @XmlEnumValue("HECS-HELP")
    HECS_HELP("HECS-HELP"),
    
    @XmlEnumValue("Hire Purchase")
    HIRE_PURCHASE("Hire Purchase"),
    
    @XmlEnumValue("Invoice Financing Loan")
    INVOICE_FINANCING_LOAN("Invoice Financing Loan"),
    
    @XmlEnumValue("Lease")
    LEASE("Lease"),
    
    @XmlEnumValue("Line of Credit")
    LINE_OF_CREDIT("Line of Credit"),
    
    @XmlEnumValue("Loan as Guarantor")
    LOAN_AS_GUARANTOR("Loan as Guarantor"),
    
    @XmlEnumValue("Margin Loan")
    MARGIN_LOAN("Margin Loan"),
    
    @XmlEnumValue("Mortgage Loan")
    MORTGAGE_LOAN("Mortgage Loan"),
    
    @XmlEnumValue("Other")
    OTHER("Other"),
    
    @XmlEnumValue("Other Loan")
    OTHER_LOAN("Other Loan"),
    
    @XmlEnumValue("Outstanding Taxation")
    OUTSTANDING_TAXATION("Outstanding Taxation"),
    
    @XmlEnumValue("Overdraft")
    OVERDRAFT("Overdraft"),
    
    @XmlEnumValue("Personal Loan")
    PERSONAL_LOAN("Personal Loan"),
    
    @XmlEnumValue("Store Card")
    STORE_CARD("Store Card"),
    
    @XmlEnumValue("Term Loan")
    TERM_LOAN("Term Loan"),
    
    @XmlEnumValue("Trade Finance Loan")
    TRADE_FINANCE_LOAN("Trade Finance Loan");
    private final String value;
    LiabilityTypeList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static LiabilityTypeList fromValue(String v) {
        for (LiabilityTypeList c: LiabilityTypeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
