//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "loanTermUnitsList")
@XmlEnum
public enum LoanTermUnitsList {
    
    @XmlEnumValue("Days")
    DAYS("Days"),
    
    @XmlEnumValue("Months")
    MONTHS("Months"),
    
    @XmlEnumValue("Weeks")
    WEEKS("Weeks"),
    
    @XmlEnumValue("Years")
    YEARS("Years");
    private final String value;
    LoanTermUnitsList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static LoanTermUnitsList fromValue(String v) {
        for (LoanTermUnitsList c: LoanTermUnitsList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
