//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "loanPaymentScheduleTypeList")
@XmlEnum
public enum LoanPaymentScheduleTypeList {
    
    @XmlEnumValue("Even Principal Payments")
    EVEN_PRINCIPAL_PAYMENTS("Even Principal Payments"),
    
    @XmlEnumValue("Even Total Payments")
    EVEN_TOTAL_PAYMENTS("Even Total Payments"),
    
    @XmlEnumValue("Half the Monthly Amount Paid in Fortnightly Payments")
    HALF_THE_MONTHLY_AMOUNT_PAID_IN_FORTNIGHTLY_PAYMENTS("Half the Monthly Amount Paid in Fortnightly Payments"),
    
    @XmlEnumValue("Minimum Payments")
    MINIMUM_PAYMENTS("Minimum Payments"),
    
    @XmlEnumValue("Outstanding Balance Based Payments")
    OUTSTANDING_BALANCE_BASED_PAYMENTS("Outstanding Balance Based Payments");
    private final String value;
    LoanPaymentScheduleTypeList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static LoanPaymentScheduleTypeList fromValue(String v) {
        for (LoanPaymentScheduleTypeList c: LoanPaymentScheduleTypeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
