//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "mitigantFactorList")
@XmlEnum
public enum MitigantFactorList {
    
    @XmlEnumValue("Application Reflects Changes")
    APPLICATION_REFLECTS_CHANGES("Application Reflects Changes"),
    
    @XmlEnumValue("Co-Applicant's Income")
    CO_APPLICANT_S_INCOME("Co-Applicant's Income"),
    
    @XmlEnumValue("Downsize of Principal Residence")
    DOWNSIZE_OF_PRINCIPAL_RESIDENCE("Downsize of Principal Residence"),
    
    @XmlEnumValue("Other")
    OTHER("Other"),
    
    @XmlEnumValue("Reducing Expenditure")
    REDUCING_EXPENDITURE("Reducing Expenditure"),
    
    @XmlEnumValue("Sale of Assets")
    SALE_OF_ASSETS("Sale of Assets"),
    
    @XmlEnumValue("Savings or Superannuation")
    SAVINGS_OR_SUPERANNUATION("Savings or Superannuation"),
    
    @XmlEnumValue("Securing Additional Income")
    SECURING_ADDITIONAL_INCOME("Securing Additional Income"),
    
    @XmlEnumValue("Using Savings")
    USING_SAVINGS("Using Savings");
    private final String value;
    MitigantFactorList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static MitigantFactorList fromValue(String v) {
        for (MitigantFactorList c: MitigantFactorList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
