//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "mobileComputingTypeList")
@XmlEnum
public enum MobileComputingTypeList {
    
    @XmlEnumValue("Laptop")
    LAPTOP("Laptop"),
    
    @XmlEnumValue("Other")
    OTHER("Other"),
    
    @XmlEnumValue("Smart Phone")
    SMART_PHONE("Smart Phone"),
    
    @XmlEnumValue("Tablet")
    TABLET("Tablet"),
    
    @XmlEnumValue("Wearable Device")
    WEARABLE_DEVICE("Wearable Device");
    private final String value;
    MobileComputingTypeList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static MobileComputingTypeList fromValue(String v) {
        for (MobileComputingTypeList c: MobileComputingTypeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
