//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "nameTitleList")
@XmlEnum
public enum NameTitleList {
    
    @XmlEnumValue("Dr")
    DR("Dr"),
    
    @XmlEnumValue("Hon")
    HON("Hon"),
    
    @XmlEnumValue("Lady")
    LADY("Lady"),
    
    @XmlEnumValue("Miss")
    MISS("Miss"),
    
    @XmlEnumValue("Mr")
    MR("Mr"),
    
    @XmlEnumValue("Mrs")
    MRS("Mrs"),
    
    @XmlEnumValue("Ms")
    MS("Ms"),
    
    @XmlEnumValue("Other")
    OTHER("Other"),
    
    @XmlEnumValue("Prof")
    PROF("Prof"),
    
    @XmlEnumValue("R Hon")
    R_HON("R Hon"),
    
    @XmlEnumValue("Rev")
    REV("Rev"),
    
    @XmlEnumValue("Sir")
    SIR("Sir");
    private final String value;
    NameTitleList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static NameTitleList fromValue(String v) {
        for (NameTitleList c: NameTitleList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
