//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "nonRealEstateSecurityPriorityList")
@XmlEnum
public enum NonRealEstateSecurityPriorityList {
    
    @XmlEnumValue("First Security Interest")
    FIRST_SECURITY_INTEREST("First Security Interest"),
    
    @XmlEnumValue("Second Security Interest")
    SECOND_SECURITY_INTEREST("Second Security Interest"),
    
    @XmlEnumValue("Third Security Interest")
    THIRD_SECURITY_INTEREST("Third Security Interest");
    private final String value;
    NonRealEstateSecurityPriorityList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static NonRealEstateSecurityPriorityList fromValue(String v) {
        for (NonRealEstateSecurityPriorityList c: NonRealEstateSecurityPriorityList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
