//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "officeEquipmentTypeList")
@XmlEnum
public enum OfficeEquipmentTypeList {
    
    @XmlEnumValue("Fixtures and Fittings")
    FIXTURES_AND_FITTINGS("Fixtures and Fittings"),
    
    @XmlEnumValue("Other")
    OTHER("Other"),
    
    @XmlEnumValue("Photocopier/Printer")
    PHOTOCOPIER_PRINTER("Photocopier/Printer"),
    
    @XmlEnumValue("Telephone Systems")
    TELEPHONE_SYSTEMS("Telephone Systems");
    private final String value;
    OfficeEquipmentTypeList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static OfficeEquipmentTypeList fromValue(String v) {
        for (OfficeEquipmentTypeList c: OfficeEquipmentTypeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
