//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "otherIncomeTypeList")
@XmlEnum
public enum OtherIncomeTypeList {
    
    @XmlEnumValue("Annuities")
    ANNUITIES("Annuities"),
    
    @XmlEnumValue("Child Maintenance")
    CHILD_MAINTENANCE("Child Maintenance"),
    
    @XmlEnumValue("Dividends")
    DIVIDENDS("Dividends"),
    
    @XmlEnumValue("Foreign Sourced")
    FOREIGN_SOURCED("Foreign Sourced"),
    
    @XmlEnumValue("Government Benefits")
    GOVERNMENT_BENEFITS("Government Benefits"),
    
    @XmlEnumValue("Interest Income")
    INTEREST_INCOME("Interest Income"),
    
    @XmlEnumValue("Other Income")
    OTHER_INCOME("Other Income"),
    
    @XmlEnumValue("Private Pension")
    PRIVATE_PENSION("Private Pension"),
    
    @XmlEnumValue("Salary Sacrifice Contribution")
    SALARY_SACRIFICE_CONTRIBUTION("Salary Sacrifice Contribution"),
    
    @XmlEnumValue("Super Concessional Contribution")
    SUPER_CONCESSIONAL_CONTRIBUTION("Super Concessional Contribution"),
    
    @XmlEnumValue("Super Excess Concessional Contribution")
    SUPER_EXCESS_CONCESSIONAL_CONTRIBUTION("Super Excess Concessional Contribution"),
    
    @XmlEnumValue("Super Non Concessional Contribution")
    SUPER_NON_CONCESSIONAL_CONTRIBUTION("Super Non Concessional Contribution"),
    
    @XmlEnumValue("Superannuation")
    SUPERANNUATION("Superannuation"),
    
    @XmlEnumValue("Workers Compensation")
    WORKERS_COMPENSATION("Workers Compensation");
    private final String value;
    OtherIncomeTypeList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static OtherIncomeTypeList fromValue(String v) {
        for (OtherIncomeTypeList c: OtherIncomeTypeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
