//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "otherExpenseTypeList")
@XmlEnum
public enum OtherExpenseTypeList {
    
    @XmlEnumValue("Additional Car(s) Maintenance")
    ADDITIONAL_CAR_S_MAINTENANCE("Additional Car(s) Maintenance"),
    
    @XmlEnumValue("Additional Car(s) Petrol")
    ADDITIONAL_CAR_S_PETROL("Additional Car(s) Petrol"),
    
    @XmlEnumValue("Additional Car(s) Registration")
    ADDITIONAL_CAR_S_REGISTRATION("Additional Car(s) Registration"),
    
    @XmlEnumValue("Board")
    BOARD("Board"),
    
    @XmlEnumValue("Body Corporate Levies")
    BODY_CORPORATE_LEVIES("Body Corporate Levies"),
    
    @XmlEnumValue("Building or Contents Insurance")
    BUILDING_OR_CONTENTS_INSURANCE("Building or Contents Insurance"),
    
    @XmlEnumValue("Child Care")
    CHILD_CARE("Child Care"),
    
    @XmlEnumValue("Child Maintenance")
    CHILD_MAINTENANCE("Child Maintenance"),
    
    @XmlEnumValue("Education")
    EDUCATION("Education"),
    
    @XmlEnumValue("Gym Membership")
    GYM_MEMBERSHIP("Gym Membership"),
    
    @XmlEnumValue("Maintenance Fee")
    MAINTENANCE_FEE("Maintenance Fee"),
    
    @XmlEnumValue("Medical")
    MEDICAL("Medical"),
    
    @XmlEnumValue("Mobile Phone(s)")
    MOBILE_PHONE_S("Mobile Phone(s)"),
    
    @XmlEnumValue("Non Government Education")
    NON_GOVERNMENT_EDUCATION("Non Government Education"),
    
    @XmlEnumValue("Other")
    OTHER("Other"),
    
    @XmlEnumValue("Private Health / Medical")
    PRIVATE_HEALTH_MEDICAL("Private Health / Medical"),
    
    @XmlEnumValue("Rent")
    RENT("Rent"),
    
    @XmlEnumValue("Subscriptions")
    SUBSCRIPTIONS("Subscriptions");
    private final String value;
    OtherExpenseTypeList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static OtherExpenseTypeList fromValue(String v) {
        for (OtherExpenseTypeList c: OtherExpenseTypeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
