//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "otherAssetTypeList")
@XmlEnum
public enum OtherAssetTypeList {
    
    @XmlEnumValue("Art Works")
    ART_WORKS("Art Works"),
    
    @XmlEnumValue("Good Will of Business")
    GOOD_WILL_OF_BUSINESS("Good Will of Business"),
    
    @XmlEnumValue("Home Contents")
    HOME_CONTENTS("Home Contents"),
    
    @XmlEnumValue("Intellectual Property")
    INTELLECTUAL_PROPERTY("Intellectual Property"),
    
    @XmlEnumValue("Other")
    OTHER("Other"),
    
    @XmlEnumValue("Stock and Inventory")
    STOCK_AND_INVENTORY("Stock and Inventory");
    private final String value;
    OtherAssetTypeList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static OtherAssetTypeList fromValue(String v) {
        for (OtherAssetTypeList c: OtherAssetTypeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
