//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "payFeesFromList")
@XmlEnum
public enum PayFeesFromList {
    
    @XmlEnumValue("Account")
    ACCOUNT("Account"),
    
    @XmlEnumValue("Add to Loan Amount")
    ADD_TO_LOAN_AMOUNT("Add to Loan Amount"),
    
    @XmlEnumValue("Cash")
    CASH("Cash"),
    
    @XmlEnumValue("Cheque")
    CHEQUE("Cheque"),
    
    @XmlEnumValue("Credit Card")
    CREDIT_CARD("Credit Card"),
    
    @XmlEnumValue("Debit Card")
    DEBIT_CARD("Debit Card"),
    
    @XmlEnumValue("Direct Credit")
    DIRECT_CREDIT("Direct Credit"),
    
    @XmlEnumValue("Direct Deposit")
    DIRECT_DEPOSIT("Direct Deposit"),
    
    @XmlEnumValue("From Settlement Proceeds")
    FROM_SETTLEMENT_PROCEEDS("From Settlement Proceeds"),
    
    @XmlEnumValue("Included in Loan Amount")
    INCLUDED_IN_LOAN_AMOUNT("Included in Loan Amount");
    private final String value;
    PayFeesFromList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static PayFeesFromList fromValue(String v) {
        for (PayFeesFromList c: PayFeesFromList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
