//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "paymentTypeList")
@XmlEnum
public enum PaymentTypeList {
    
    @XmlEnumValue("Interest Capitalised")
    INTEREST_CAPITALISED("Interest Capitalised"),
    
    @XmlEnumValue("Interest Only")
    INTEREST_ONLY("Interest Only"),
    
    @XmlEnumValue("Prepaid Interest")
    PREPAID_INTEREST("Prepaid Interest"),
    
    @XmlEnumValue("Principal and Interest")
    PRINCIPAL_AND_INTEREST("Principal and Interest"),
    
    @XmlEnumValue("Principal Interest Fees")
    PRINCIPAL_INTEREST_FEES("Principal Interest Fees");
    private final String value;
    PaymentTypeList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static PaymentTypeList fromValue(String v) {
        for (PaymentTypeList c: PaymentTypeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
