//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlType;
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "percentOwnedType", propOrder = {
    "owner"
})
public class PercentOwnedType {
    @XmlElement(name = "Owner")
    protected List<PercentOwnedType.Owner> owner;
    @XmlAttribute(name = "Proportions")
    protected ProportionsList proportions;
    
    public List<PercentOwnedType.Owner> getOwner() {
        if (owner == null) {
            owner = new ArrayList<PercentOwnedType.Owner>();
        }
        return this.owner;
    }
    
    public ProportionsList getProportions() {
        return proportions;
    }
    
    public void setProportions(ProportionsList value) {
        this.proportions = value;
    }
    
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Owner {
        @XmlAttribute(name = "Percent")
        protected BigDecimal percent;
        @XmlAttribute(name = "x_Party")
        @XmlIDREF
        protected Object xParty;
        
        public BigDecimal getPercent() {
            return percent;
        }
        
        public void setPercent(BigDecimal value) {
            this.percent = value;
        }
        
        public Object getXParty() {
            return xParty;
        }
        
        public void setXParty(Object value) {
            this.xParty = value;
        }
    }
}
