//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "personNameType")
public class PersonNameType {
    @XmlAttribute(name = "FirstName")
    protected String firstName;
    @XmlAttribute(name = "KnownAs")
    protected String knownAs;
    @XmlAttribute(name = "MiddleNames")
    protected String middleNames;
    @XmlAttribute(name = "NameTitle")
    protected NameTitleList nameTitle;
    @XmlAttribute(name = "OtherNameTitle")
    protected String otherNameTitle;
    @XmlAttribute(name = "Surname")
    protected String surname;
    
    public String getFirstName() {
        return firstName;
    }
    
    public void setFirstName(String value) {
        this.firstName = value;
    }
    
    public String getKnownAs() {
        return knownAs;
    }
    
    public void setKnownAs(String value) {
        this.knownAs = value;
    }
    
    public String getMiddleNames() {
        return middleNames;
    }
    
    public void setMiddleNames(String value) {
        this.middleNames = value;
    }
    
    public NameTitleList getNameTitle() {
        return nameTitle;
    }
    
    public void setNameTitle(NameTitleList value) {
        this.nameTitle = value;
    }
    
    public String getOtherNameTitle() {
        return otherNameTitle;
    }
    
    public void setOtherNameTitle(String value) {
        this.otherNameTitle = value;
    }
    
    public String getSurname() {
        return surname;
    }
    
    public void setSurname(String value) {
        this.surname = value;
    }
}
