//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "plantEquipmentAndIndustrialTypeList")
@XmlEnum
public enum PlantEquipmentAndIndustrialTypeList {
    
    @XmlEnumValue("Arborist and Landscaping Equipment")
    ARBORIST_AND_LANDSCAPING_EQUIPMENT("Arborist and Landscaping Equipment"),
    
    @XmlEnumValue("Butchers Plant")
    BUTCHERS_PLANT("Butchers Plant"),
    
    @XmlEnumValue("Cleaning")
    CLEANING("Cleaning"),
    
    @XmlEnumValue("Compressors")
    COMPRESSORS("Compressors"),
    
    @XmlEnumValue("Engine")
    ENGINE("Engine"),
    
    @XmlEnumValue("Engineering Machine")
    ENGINEERING_MACHINE("Engineering Machine"),
    
    @XmlEnumValue("Fitout")
    FITOUT("Fitout"),
    
    @XmlEnumValue("Generator")
    GENERATOR("Generator"),
    
    @XmlEnumValue("Heating and Cooling")
    HEATING_AND_COOLING("Heating and Cooling"),
    
    @XmlEnumValue("Hot Water Plant")
    HOT_WATER_PLANT("Hot Water Plant"),
    
    @XmlEnumValue("Lighting Plant")
    LIGHTING_PLANT("Lighting Plant"),
    
    @XmlEnumValue("Manufacturing and Machining")
    MANUFACTURING_AND_MACHINING("Manufacturing and Machining"),
    
    @XmlEnumValue("Other")
    OTHER("Other"),
    
    @XmlEnumValue("Photo Process Plant")
    PHOTO_PROCESS_PLANT("Photo Process Plant"),
    
    @XmlEnumValue("Power Metering Equipment")
    POWER_METERING_EQUIPMENT("Power Metering Equipment"),
    
    @XmlEnumValue("Printing Press")
    PRINTING_PRESS("Printing Press"),
    
    @XmlEnumValue("Pump")
    PUMP("Pump"),
    
    @XmlEnumValue("Sewing Machine")
    SEWING_MACHINE("Sewing Machine"),
    
    @XmlEnumValue("Solar DC Inverters")
    SOLAR_DC_INVERTERS("Solar DC Inverters"),
    
    @XmlEnumValue("Solar Rooftop PV")
    SOLAR_ROOFTOP_PV("Solar Rooftop PV"),
    
    @XmlEnumValue("Wood Working Plant")
    WOOD_WORKING_PLANT("Wood Working Plant");
    private final String value;
    PlantEquipmentAndIndustrialTypeList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static PlantEquipmentAndIndustrialTypeList fromValue(String v) {
        for (PlantEquipmentAndIndustrialTypeList c: PlantEquipmentAndIndustrialTypeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
