//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "poBoxTypeList")
@XmlEnum
public enum PoBoxTypeList {
    
    @XmlEnumValue("Care of Post Office")
    CARE_OF_POST_OFFICE("Care of Post Office"),
    
    @XmlEnumValue("Community Mail Agent")
    COMMUNITY_MAIL_AGENT("Community Mail Agent"),
    
    @XmlEnumValue("Community Mail Bag")
    COMMUNITY_MAIL_BAG("Community Mail Bag"),
    
    @XmlEnumValue("Community Postal Agent")
    COMMUNITY_POSTAL_AGENT("Community Postal Agent"),
    
    @XmlEnumValue("Freepost")
    FREEPOST("Freepost"),
    
    @XmlEnumValue("GPO Box")
    GPO_BOX("GPO Box"),
    
    @XmlEnumValue("Locked Bag")
    LOCKED_BAG("Locked Bag"),
    
    @XmlEnumValue("Mail Bag")
    MAIL_BAG("Mail Bag"),
    
    @XmlEnumValue("Mail Service")
    MAIL_SERVICE("Mail Service"),
    
    @XmlEnumValue("PO Box")
    PO_BOX("PO Box"),
    
    @XmlEnumValue("Postal Mail Bag")
    POSTAL_MAIL_BAG("Postal Mail Bag"),
    
    @XmlEnumValue("Poste Restante")
    POSTE_RESTANTE("Poste Restante"),
    
    @XmlEnumValue("Private Bag")
    PRIVATE_BAG("Private Bag"),
    
    @XmlEnumValue("Roadside Delivery")
    ROADSIDE_DELIVERY("Roadside Delivery"),
    
    @XmlEnumValue("Roadside Mail Bag")
    ROADSIDE_MAIL_BAG("Roadside Mail Bag"),
    
    @XmlEnumValue("Roadside Mail Box")
    ROADSIDE_MAIL_BOX("Roadside Mail Box"),
    
    @XmlEnumValue("Roadside Mail Service")
    ROADSIDE_MAIL_SERVICE("Roadside Mail Service"),
    
    @XmlEnumValue("Rural Mail Bag")
    RURAL_MAIL_BAG("Rural Mail Bag");
    private final String value;
    PoBoxTypeList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static PoBoxTypeList fromValue(String v) {
        for (PoBoxTypeList c: PoBoxTypeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
