//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "preConditionToStageApplicationInstructionsList")
@XmlEnum
public enum PreConditionToStageApplicationInstructionsList {
    
    @XmlEnumValue("Conditional Approval")
    CONDITIONAL_APPROVAL("Conditional Approval"),
    
    @XmlEnumValue("PreApproval")
    PRE_APPROVAL("PreApproval"),
    
    @XmlEnumValue("Referred to Assessor")
    REFERRED_TO_ASSESSOR("Referred to Assessor"),
    
    @XmlEnumValue("Settlement")
    SETTLEMENT("Settlement"),
    
    @XmlEnumValue("Unconditional Approval")
    UNCONDITIONAL_APPROVAL("Unconditional Approval");
    private final String value;
    PreConditionToStageApplicationInstructionsList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static PreConditionToStageApplicationInstructionsList fromValue(String v) {
        for (PreConditionToStageApplicationInstructionsList c: PreConditionToStageApplicationInstructionsList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
