//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "primaryPurposeLoanPurposeList")
@XmlEnum
public enum PrimaryPurposeLoanPurposeList {
    
    @XmlEnumValue("Business")
    BUSINESS("Business"),
    
    @XmlEnumValue("Investment Non Residential")
    INVESTMENT_NON_RESIDENTIAL("Investment Non Residential"),
    
    @XmlEnumValue("Investment Residential")
    INVESTMENT_RESIDENTIAL("Investment Residential"),
    
    @XmlEnumValue("Owner Occupied")
    OWNER_OCCUPIED("Owner Occupied"),
    
    @XmlEnumValue("Personal")
    PERSONAL("Personal");
    private final String value;
    PrimaryPurposeLoanPurposeList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static PrimaryPurposeLoanPurposeList fromValue(String v) {
        for (PrimaryPurposeLoanPurposeList c: PrimaryPurposeLoanPurposeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
