//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "principalRefinancingReasonList")
@XmlEnum
public enum PrincipalRefinancingReasonList {
    
    @XmlEnumValue("Consolidating or Restructuring Finances")
    CONSOLIDATING_OR_RESTRUCTURING_FINANCES("Consolidating or Restructuring Finances"),
    
    @XmlEnumValue("Convenience / Flexibility")
    CONVENIENCE_FLEXIBILITY("Convenience / Flexibility"),
    
    @XmlEnumValue("Dissatisfaction with Service at Current Lender")
    DISSATISFACTION_WITH_SERVICE_AT_CURRENT_LENDER("Dissatisfaction with Service at Current Lender"),
    
    @XmlEnumValue("More Competitive Pricing")
    MORE_COMPETITIVE_PRICING("More Competitive Pricing"),
    
    @XmlEnumValue("Specific Product or Feature")
    SPECIFIC_PRODUCT_OR_FEATURE("Specific Product or Feature");
    private final String value;
    PrincipalRefinancingReasonList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static PrincipalRefinancingReasonList fromValue(String v) {
        for (PrincipalRefinancingReasonList c: PrincipalRefinancingReasonList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
