//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "proofCodeOtherList")
@XmlEnum
public enum ProofCodeOtherList {
    
    @XmlEnumValue("Letter from Appropriate Body")
    LETTER_FROM_APPROPRIATE_BODY("Letter from Appropriate Body"),
    
    @XmlEnumValue("Letter from Government")
    LETTER_FROM_GOVERNMENT("Letter from Government"),
    
    @XmlEnumValue("Tax Return")
    TAX_RETURN("Tax Return");
    private final String value;
    ProofCodeOtherList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static ProofCodeOtherList fromValue(String v) {
        for (ProofCodeOtherList c: ProofCodeOtherList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
