//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "proposedRepaymentMethodList")
@XmlEnum
public enum ProposedRepaymentMethodList {
    
    @XmlEnumValue("Australia Post")
    AUSTRALIA_POST("Australia Post"),
    
    @XmlEnumValue("Bpay")
    BPAY("Bpay"),
    
    @XmlEnumValue("Credit Card")
    CREDIT_CARD("Credit Card"),
    
    @XmlEnumValue("Direct Debit Existing Account")
    DIRECT_DEBIT_EXISTING_ACCOUNT("Direct Debit Existing Account"),
    
    @XmlEnumValue("Direct Debit New Account")
    DIRECT_DEBIT_NEW_ACCOUNT("Direct Debit New Account"),
    
    @XmlEnumValue("Direct Salary Credit")
    DIRECT_SALARY_CREDIT("Direct Salary Credit"),
    
    @XmlEnumValue("Funds Transfer")
    FUNDS_TRANSFER("Funds Transfer"),
    
    @XmlEnumValue("Lender Branch")
    LENDER_BRANCH("Lender Branch"),
    
    @XmlEnumValue("Other")
    OTHER("Other"),
    
    @XmlEnumValue("Staff Pay")
    STAFF_PAY("Staff Pay");
    private final String value;
    ProposedRepaymentMethodList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static ProposedRepaymentMethodList fromValue(String v) {
        for (ProposedRepaymentMethodList c: ProposedRepaymentMethodList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
