//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "realEstateAssetEncumbranceList")
@XmlEnum
public enum RealEstateAssetEncumbranceList {
    
    @XmlEnumValue("Caveat")
    CAVEAT("Caveat"),
    
    @XmlEnumValue("Charge")
    CHARGE("Charge"),
    
    @XmlEnumValue("Covenant")
    COVENANT("Covenant"),
    
    @XmlEnumValue("Easement")
    EASEMENT("Easement"),
    
    @XmlEnumValue("FiFa")
    FI_FA("FiFa"),
    
    @XmlEnumValue("Land Tax Charge")
    LAND_TAX_CHARGE("Land Tax Charge"),
    
    @XmlEnumValue("Lease")
    LEASE("Lease"),
    
    @XmlEnumValue("Memorial")
    MEMORIAL("Memorial"),
    
    @XmlEnumValue("Mortgage")
    MORTGAGE("Mortgage"),
    
    @XmlEnumValue("None Disclosed")
    NONE_DISCLOSED("None Disclosed"),
    
    @XmlEnumValue("Not Known")
    NOT_KNOWN("Not Known"),
    
    @XmlEnumValue("Other")
    OTHER("Other"),
    
    @XmlEnumValue("Warrant")
    WARRANT("Warrant"),
    
    @XmlEnumValue("Writ")
    WRIT("Writ");
    private final String value;
    RealEstateAssetEncumbranceList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static RealEstateAssetEncumbranceList fromValue(String v) {
        for (RealEstateAssetEncumbranceList c: RealEstateAssetEncumbranceList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
