//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "residentialTypeList")
@XmlEnum
public enum ResidentialTypeList {
    
    @XmlEnumValue("Aged Care Unit")
    AGED_CARE_UNIT("Aged Care Unit"),
    
    @XmlEnumValue("Apartment Unit Flat")
    APARTMENT_UNIT_FLAT("Apartment Unit Flat"),
    
    @XmlEnumValue("Bedsitter Bachelor")
    BEDSITTER_BACHELOR("Bedsitter Bachelor"),
    
    @XmlEnumValue("Company Title Unit")
    COMPANY_TITLE_UNIT("Company Title Unit"),
    
    @XmlEnumValue("Converted Commercial Property")
    CONVERTED_COMMERCIAL_PROPERTY("Converted Commercial Property"),
    
    @XmlEnumValue("Converted Industrial Property")
    CONVERTED_INDUSTRIAL_PROPERTY("Converted Industrial Property"),
    
    @XmlEnumValue("Converted Motel Units")
    CONVERTED_MOTEL_UNITS("Converted Motel Units"),
    
    @XmlEnumValue("Display House")
    DISPLAY_HOUSE("Display House"),
    
    @XmlEnumValue("Duplex")
    DUPLEX("Duplex"),
    
    @XmlEnumValue("Fully Detached House")
    FULLY_DETACHED_HOUSE("Fully Detached House"),
    
    @XmlEnumValue("High Density Apartment")
    HIGH_DENSITY_APARTMENT("High Density Apartment"),
    
    @XmlEnumValue("Holiday Home")
    HOLIDAY_HOME("Holiday Home"),
    
    @XmlEnumValue("Holiday Rental")
    HOLIDAY_RENTAL("Holiday Rental"),
    
    @XmlEnumValue("Improved Land")
    IMPROVED_LAND("Improved Land"),
    
    @XmlEnumValue("Kit Home")
    KIT_HOME("Kit Home"),
    
    @XmlEnumValue("Low Density Apartment")
    LOW_DENSITY_APARTMENT("Low Density Apartment"),
    
    @XmlEnumValue("Luxury House")
    LUXURY_HOUSE("Luxury House"),
    
    @XmlEnumValue("Luxury Other")
    LUXURY_OTHER("Luxury Other"),
    
    @XmlEnumValue("Medium Density Apartment")
    MEDIUM_DENSITY_APARTMENT("Medium Density Apartment"),
    
    @XmlEnumValue("Property Development")
    PROPERTY_DEVELOPMENT("Property Development"),
    
    @XmlEnumValue("Relocatable Home")
    RELOCATABLE_HOME("Relocatable Home"),
    
    @XmlEnumValue("Resort Unit")
    RESORT_UNIT("Resort Unit"),
    
    @XmlEnumValue("Semi Detached House")
    SEMI_DETACHED_HOUSE("Semi Detached House"),
    
    @XmlEnumValue("Serviced Apartment")
    SERVICED_APARTMENT("Serviced Apartment"),
    
    @XmlEnumValue("Strata Hotel Unit")
    STRATA_HOTEL_UNIT("Strata Hotel Unit"),
    
    @XmlEnumValue("Strata Title Unit")
    STRATA_TITLE_UNIT("Strata Title Unit"),
    
    @XmlEnumValue("Studio Warehouse Apartment")
    STUDIO_WAREHOUSE_APARTMENT("Studio Warehouse Apartment"),
    
    @XmlEnumValue("Terrace")
    TERRACE("Terrace"),
    
    @XmlEnumValue("Townhouse")
    TOWNHOUSE("Townhouse"),
    
    @XmlEnumValue("Unit Student Accommodation")
    UNIT_STUDENT_ACCOMMODATION("Unit Student Accommodation"),
    
    @XmlEnumValue("Vacant Land")
    VACANT_LAND("Vacant Land"),
    
    @XmlEnumValue("Villa")
    VILLA("Villa");
    private final String value;
    ResidentialTypeList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static ResidentialTypeList fromValue(String v) {
        for (ResidentialTypeList c: ResidentialTypeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
