//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "responsibleLendingType", propOrder = {
    "mitigant",
    "significantChange"
})
public class ResponsibleLendingType {
    @XmlElement(name = "Mitigant")
    protected List<ResponsibleLendingType.Mitigant> mitigant;
    @XmlElement(name = "SignificantChange")
    protected List<ResponsibleLendingType.SignificantChange> significantChange;
    @XmlAttribute(name = "AnticipatedChanges")
    protected YesNoList anticipatedChanges;
    
    public List<ResponsibleLendingType.Mitigant> getMitigant() {
        if (mitigant == null) {
            mitigant = new ArrayList<ResponsibleLendingType.Mitigant>();
        }
        return this.mitigant;
    }
    
    public List<ResponsibleLendingType.SignificantChange> getSignificantChange() {
        if (significantChange == null) {
            significantChange = new ArrayList<ResponsibleLendingType.SignificantChange>();
        }
        return this.significantChange;
    }
    
    public YesNoList getAnticipatedChanges() {
        return anticipatedChanges;
    }
    
    public void setAnticipatedChanges(YesNoList value) {
        this.anticipatedChanges = value;
    }
    
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "saleOfAssets",
        "savingsOrSuperannuation"
    })
    public static class Mitigant {
        @XmlElement(name = "SaleOfAssets")
        protected ResponsibleLendingType.Mitigant.SaleOfAssets saleOfAssets;
        @XmlElement(name = "SavingsOrSuperannuation")
        protected ResponsibleLendingType.Mitigant.SavingsOrSuperannuation savingsOrSuperannuation;
        @XmlAttribute(name = "Description")
        protected String description;
        @XmlAttribute(name = "Factor")
        protected MitigantFactorList factor;
        @XmlAttribute(name = "UniqueID")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlID
        protected String uniqueID;
        
        public ResponsibleLendingType.Mitigant.SaleOfAssets getSaleOfAssets() {
            return saleOfAssets;
        }
        
        public void setSaleOfAssets(ResponsibleLendingType.Mitigant.SaleOfAssets value) {
            this.saleOfAssets = value;
        }
        
        public ResponsibleLendingType.Mitigant.SavingsOrSuperannuation getSavingsOrSuperannuation() {
            return savingsOrSuperannuation;
        }
        
        public void setSavingsOrSuperannuation(ResponsibleLendingType.Mitigant.SavingsOrSuperannuation value) {
            this.savingsOrSuperannuation = value;
        }
        
        public String getDescription() {
            return description;
        }
        
        public void setDescription(String value) {
            this.description = value;
        }
        
        public MitigantFactorList getFactor() {
            return factor;
        }
        
        public void setFactor(MitigantFactorList value) {
            this.factor = value;
        }
        
        public String getUniqueID() {
            return uniqueID;
        }
        
        public void setUniqueID(String value) {
            this.uniqueID = value;
        }
        
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class SaleOfAssets {
            @XmlAttribute(name = "LenderHeldSecurity")
            protected YesNoList lenderHeldSecurity;
            @XmlAttribute(name = "LenderHeldSecurityDescription")
            protected String lenderHeldSecurityDescription;
            @XmlAttribute(name = "OtherAssets")
            protected YesNoList otherAssets;
            @XmlAttribute(name = "OtherAssetsDescription")
            protected String otherAssetsDescription;
            @XmlAttribute(name = "OtherLenderHeldSecurity")
            protected YesNoList otherLenderHeldSecurity;
            @XmlAttribute(name = "OtherLenderHeldSecurityDescription")
            protected String otherLenderHeldSecurityDescription;
            @XmlAttribute(name = "Shares")
            protected YesNoList shares;
            @XmlAttribute(name = "SharesDescription")
            protected String sharesDescription;
            
            public YesNoList getLenderHeldSecurity() {
                return lenderHeldSecurity;
            }
            
            public void setLenderHeldSecurity(YesNoList value) {
                this.lenderHeldSecurity = value;
            }
            
            public String getLenderHeldSecurityDescription() {
                return lenderHeldSecurityDescription;
            }
            
            public void setLenderHeldSecurityDescription(String value) {
                this.lenderHeldSecurityDescription = value;
            }
            
            public YesNoList getOtherAssets() {
                return otherAssets;
            }
            
            public void setOtherAssets(YesNoList value) {
                this.otherAssets = value;
            }
            
            public String getOtherAssetsDescription() {
                return otherAssetsDescription;
            }
            
            public void setOtherAssetsDescription(String value) {
                this.otherAssetsDescription = value;
            }
            
            public YesNoList getOtherLenderHeldSecurity() {
                return otherLenderHeldSecurity;
            }
            
            public void setOtherLenderHeldSecurity(YesNoList value) {
                this.otherLenderHeldSecurity = value;
            }
            
            public String getOtherLenderHeldSecurityDescription() {
                return otherLenderHeldSecurityDescription;
            }
            
            public void setOtherLenderHeldSecurityDescription(String value) {
                this.otherLenderHeldSecurityDescription = value;
            }
            
            public YesNoList getShares() {
                return shares;
            }
            
            public void setShares(YesNoList value) {
                this.shares = value;
            }
            
            public String getSharesDescription() {
                return sharesDescription;
            }
            
            public void setSharesDescription(String value) {
                this.sharesDescription = value;
            }
        }
        
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class SavingsOrSuperannuation {
            @XmlAttribute(name = "LenderHeldSavingsAccount")
            protected YesNoList lenderHeldSavingsAccount;
            @XmlAttribute(name = "LenderHeldSavingsAccountDescription")
            protected String lenderHeldSavingsAccountDescription;
            @XmlAttribute(name = "OtherLenderHeldSavingsAccount")
            protected YesNoList otherLenderHeldSavingsAccount;
            @XmlAttribute(name = "OtherLenderHeldSavingsAccountDescription")
            protected String otherLenderHeldSavingsAccountDescription;
            
            public YesNoList getLenderHeldSavingsAccount() {
                return lenderHeldSavingsAccount;
            }
            
            public void setLenderHeldSavingsAccount(YesNoList value) {
                this.lenderHeldSavingsAccount = value;
            }
            
            public String getLenderHeldSavingsAccountDescription() {
                return lenderHeldSavingsAccountDescription;
            }
            
            public void setLenderHeldSavingsAccountDescription(String value) {
                this.lenderHeldSavingsAccountDescription = value;
            }
            
            public YesNoList getOtherLenderHeldSavingsAccount() {
                return otherLenderHeldSavingsAccount;
            }
            
            public void setOtherLenderHeldSavingsAccount(YesNoList value) {
                this.otherLenderHeldSavingsAccount = value;
            }
            
            public String getOtherLenderHeldSavingsAccountDescription() {
                return otherLenderHeldSavingsAccountDescription;
            }
            
            public void setOtherLenderHeldSavingsAccountDescription(String value) {
                this.otherLenderHeldSavingsAccountDescription = value;
            }
        }
    }
    
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class SignificantChange {
        @XmlAttribute(name = "Change")
        protected SignificantChangeList change;
        @XmlAttribute(name = "Description")
        protected String description;
        @XmlAttribute(name = "EndDate")
        protected XMLGregorianCalendar endDate;
        @XmlAttribute(name = "MonthlyFinancialImpact")
        protected BigDecimal monthlyFinancialImpact;
        @XmlAttribute(name = "StartDate")
        protected XMLGregorianCalendar startDate;
        @XmlAttribute(name = "UniqueID")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlID
        protected String uniqueID;
        
        public SignificantChangeList getChange() {
            return change;
        }
        
        public void setChange(SignificantChangeList value) {
            this.change = value;
        }
        
        public String getDescription() {
            return description;
        }
        
        public void setDescription(String value) {
            this.description = value;
        }
        
        public XMLGregorianCalendar getEndDate() {
            return endDate;
        }
        
        public void setEndDate(XMLGregorianCalendar value) {
            this.endDate = value;
        }
        
        public BigDecimal getMonthlyFinancialImpact() {
            return monthlyFinancialImpact;
        }
        
        public void setMonthlyFinancialImpact(BigDecimal value) {
            this.monthlyFinancialImpact = value;
        }
        
        public XMLGregorianCalendar getStartDate() {
            return startDate;
        }
        
        public void setStartDate(XMLGregorianCalendar value) {
            this.startDate = value;
        }
        
        public String getUniqueID() {
            return uniqueID;
        }
        
        public void setUniqueID(String value) {
            this.uniqueID = value;
        }
    }
}
