//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "salesChannelTypeList")
@XmlEnum
public enum SalesChannelTypeList {
    
    @XmlEnumValue("Branch Network")
    BRANCH_NETWORK("Branch Network"),
    
    @XmlEnumValue("Call Centre")
    CALL_CENTRE("Call Centre"),
    
    @XmlEnumValue("Mortgage Broker")
    MORTGAGE_BROKER("Mortgage Broker"),
    
    @XmlEnumValue("Mortgage Manager")
    MORTGAGE_MANAGER("Mortgage Manager"),
    
    @XmlEnumValue("Mortgage Originator")
    MORTGAGE_ORIGINATOR("Mortgage Originator"),
    
    @XmlEnumValue("Online Channel")
    ONLINE_CHANNEL("Online Channel");
    private final String value;
    SalesChannelTypeList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static SalesChannelTypeList fromValue(String v) {
        for (SalesChannelTypeList c: SalesChannelTypeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
