//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "securityPriorityList")
@XmlEnum
public enum SecurityPriorityList {
    
    @XmlEnumValue("First Mortgage")
    FIRST_MORTGAGE("First Mortgage"),
    
    @XmlEnumValue("Registered Security")
    REGISTERED_SECURITY("Registered Security"),
    
    @XmlEnumValue("Second after DSH")
    SECOND_AFTER_DSH("Second after DSH"),
    
    @XmlEnumValue("Second Mortgage")
    SECOND_MORTGAGE("Second Mortgage"),
    
    @XmlEnumValue("Third Mortgage")
    THIRD_MORTGAGE("Third Mortgage"),
    
    @XmlEnumValue("Unregistered Mortgage")
    UNREGISTERED_MORTGAGE("Unregistered Mortgage");
    private final String value;
    SecurityPriorityList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static SecurityPriorityList fromValue(String v) {
        for (SecurityPriorityList c: SecurityPriorityList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
