//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "securityAgreementType")
public class SecurityAgreementType {
    @XmlAttribute(name = "Held")
    protected YesNoList held;
    @XmlAttribute(name = "ToBeDischarged")
    protected YesNoList toBeDischarged;
    @XmlAttribute(name = "Type")
    protected String type;
    
    public YesNoList getHeld() {
        return held;
    }
    
    public void setHeld(YesNoList value) {
        this.held = value;
    }
    
    public YesNoList getToBeDischarged() {
        return toBeDischarged;
    }
    
    public void setToBeDischarged(YesNoList value) {
        this.toBeDischarged = value;
    }
    
    public String getType() {
        return type;
    }
    
    public void setType(String value) {
        this.type = value;
    }
}
