//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "selfEmployedBasisList")
@XmlEnum
public enum SelfEmployedBasisList {
    
    @XmlEnumValue("Casual")
    CASUAL("Casual"),
    
    @XmlEnumValue("Contract")
    CONTRACT("Contract"),
    
    @XmlEnumValue("Full Time")
    FULL_TIME("Full Time"),
    
    @XmlEnumValue("Part Time")
    PART_TIME("Part Time"),
    
    @XmlEnumValue("Temporary")
    TEMPORARY("Temporary");
    private final String value;
    SelfEmployedBasisList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static SelfEmployedBasisList fromValue(String v) {
        for (SelfEmployedBasisList c: SelfEmployedBasisList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
