//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "shareTypeList")
@XmlEnum
public enum ShareTypeList {
    
    @XmlEnumValue("Bearer Securities")
    BEARER_SECURITIES("Bearer Securities"),
    
    @XmlEnumValue("Debentures")
    DEBENTURES("Debentures"),
    
    @XmlEnumValue("Inscribed Stock Cth")
    INSCRIBED_STOCK_CTH("Inscribed Stock Cth"),
    
    @XmlEnumValue("Inscribed Stock State")
    INSCRIBED_STOCK_STATE("Inscribed Stock State"),
    
    @XmlEnumValue("Listed Shares")
    LISTED_SHARES("Listed Shares"),
    
    @XmlEnumValue("Options")
    OPTIONS("Options"),
    
    @XmlEnumValue("Unlisted Shares")
    UNLISTED_SHARES("Unlisted Shares");
    private final String value;
    ShareTypeList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static ShareTypeList fromValue(String v) {
        for (ShareTypeList c: ShareTypeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
