//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "signatureType", propOrder = {
    "capacity",
    "contact"
})
public class SignatureType {
    @XmlElement(name = "Capacity")
    protected SignatureType.Capacity capacity;
    @XmlElement(name = "Contact")
    protected SignatureType.Contact contact;
    @XmlAttribute(name = "Date")
    protected XMLGregorianCalendar date;
    @XmlAttribute(name = "ElectronicSignature")
    protected YesNoList electronicSignature;
    @XmlAttribute(name = "Rank")
    protected BigInteger rank;
    @XmlAttribute(name = "UniqueID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String uniqueID;
    @XmlAttribute(name = "x_Signatory")
    @XmlIDREF
    protected Object xSignatory;
    
    public SignatureType.Capacity getCapacity() {
        return capacity;
    }
    
    public void setCapacity(SignatureType.Capacity value) {
        this.capacity = value;
    }
    
    public SignatureType.Contact getContact() {
        return contact;
    }
    
    public void setContact(SignatureType.Contact value) {
        this.contact = value;
    }
    
    public XMLGregorianCalendar getDate() {
        return date;
    }
    
    public void setDate(XMLGregorianCalendar value) {
        this.date = value;
    }
    
    public YesNoList getElectronicSignature() {
        return electronicSignature;
    }
    
    public void setElectronicSignature(YesNoList value) {
        this.electronicSignature = value;
    }
    
    public BigInteger getRank() {
        return rank;
    }
    
    public void setRank(BigInteger value) {
        this.rank = value;
    }
    
    public String getUniqueID() {
        return uniqueID;
    }
    
    public void setUniqueID(String value) {
        this.uniqueID = value;
    }
    
    public Object getXSignatory() {
        return xSignatory;
    }
    
    public void setXSignatory(Object value) {
        this.xSignatory = value;
    }
    
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Capacity {
        @XmlAttribute(name = "Type")
        protected CapacityTypeList type;
        @XmlAttribute(name = "x_ParentEntity")
        @XmlIDREF
        protected Object xParentEntity;
        @XmlAttribute(name = "x_ProductSet")
        @XmlIDREF
        protected Object xProductSet;
        
        public CapacityTypeList getType() {
            return type;
        }
        
        public void setType(CapacityTypeList value) {
            this.type = value;
        }
        
        public Object getXParentEntity() {
            return xParentEntity;
        }
        
        public void setXParentEntity(Object value) {
            this.xParentEntity = value;
        }
        
        public Object getXProductSet() {
            return xProductSet;
        }
        
        public void setXProductSet(Object value) {
            this.xProductSet = value;
        }
    }
    
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "mobile"
    })
    public static class Contact {
        @XmlElement(name = "Mobile")
        protected PhoneType mobile;
        @XmlAttribute(name = "Email")
        protected String email;
        
        public PhoneType getMobile() {
            return mobile;
        }
        
        public void setMobile(PhoneType value) {
            this.mobile = value;
        }
        
        public String getEmail() {
            return email;
        }
        
        public void setEmail(String value) {
            this.email = value;
        }
    }
}
