//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "sourceOfFundsTypeList")
@XmlEnum
public enum SourceOfFundsTypeList {
    
    @XmlEnumValue("Business Ownership")
    BUSINESS_OWNERSHIP("Business Ownership"),
    
    @XmlEnumValue("Business Sourced Income")
    BUSINESS_SOURCED_INCOME("Business Sourced Income"),
    
    @XmlEnumValue("Company Sale or Earnings")
    COMPANY_SALE_OR_EARNINGS("Company Sale or Earnings"),
    
    @XmlEnumValue("Directorship")
    DIRECTORSHIP("Directorship"),
    
    @XmlEnumValue("Divorce Settlement")
    DIVORCE_SETTLEMENT("Divorce Settlement"),
    
    @XmlEnumValue("Employment Income")
    EMPLOYMENT_INCOME("Employment Income"),
    
    @XmlEnumValue("Gift")
    GIFT("Gift"),
    
    @XmlEnumValue("Government Benefit")
    GOVERNMENT_BENEFIT("Government Benefit"),
    
    @XmlEnumValue("Grant")
    GRANT("Grant"),
    
    @XmlEnumValue("Inheritance")
    INHERITANCE("Inheritance"),
    
    @XmlEnumValue("Insurance Settlement Proceeds")
    INSURANCE_SETTLEMENT_PROCEEDS("Insurance Settlement Proceeds"),
    
    @XmlEnumValue("Investment Income")
    INVESTMENT_INCOME("Investment Income"),
    
    @XmlEnumValue("Lottery")
    LOTTERY("Lottery"),
    
    @XmlEnumValue("Other")
    OTHER("Other"),
    
    @XmlEnumValue("Parental Support")
    PARENTAL_SUPPORT("Parental Support"),
    
    @XmlEnumValue("Payroll")
    PAYROLL("Payroll"),
    
    @XmlEnumValue("Pension")
    PENSION("Pension"),
    
    @XmlEnumValue("Personal Savings")
    PERSONAL_SAVINGS("Personal Savings"),
    
    @XmlEnumValue("Rental Income")
    RENTAL_INCOME("Rental Income"),
    
    @XmlEnumValue("Royalties")
    ROYALTIES("Royalties"),
    
    @XmlEnumValue("Sale of Asset")
    SALE_OF_ASSET("Sale of Asset"),
    
    @XmlEnumValue("Sale of Real Estate Asset")
    SALE_OF_REAL_ESTATE_ASSET("Sale of Real Estate Asset"),
    
    @XmlEnumValue("Scholarship")
    SCHOLARSHIP("Scholarship"),
    
    @XmlEnumValue("Significant Other")
    SIGNIFICANT_OTHER("Significant Other"),
    
    @XmlEnumValue("Top Executive")
    TOP_EXECUTIVE("Top Executive"),
    
    @XmlEnumValue("Trust Fund")
    TRUST_FUND("Trust Fund");
    private final String value;
    SourceOfFundsTypeList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static SourceOfFundsTypeList fromValue(String v) {
        for (SourceOfFundsTypeList c: SourceOfFundsTypeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
