//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "streetSuffixList")
@XmlEnum
public enum StreetSuffixList {
    
    @XmlEnumValue("Central")
    CENTRAL("Central"),
    
    @XmlEnumValue("Deviation")
    DEVIATION("Deviation"),
    
    @XmlEnumValue("East")
    EAST("East"),
    
    @XmlEnumValue("Extension")
    EXTENSION("Extension"),
    
    @XmlEnumValue("Inner")
    INNER("Inner"),
    
    @XmlEnumValue("Lower")
    LOWER("Lower"),
    
    @XmlEnumValue("Mall")
    MALL("Mall"),
    
    @XmlEnumValue("North")
    NORTH("North"),
    
    @XmlEnumValue("North East")
    NORTH_EAST("North East"),
    
    @XmlEnumValue("North West")
    NORTH_WEST("North West"),
    
    @XmlEnumValue("Off")
    OFF("Off"),
    
    @XmlEnumValue("On")
    ON("On"),
    
    @XmlEnumValue("Outer")
    OUTER("Outer"),
    
    @XmlEnumValue("Overpass")
    OVERPASS("Overpass"),
    
    @XmlEnumValue("South")
    SOUTH("South"),
    
    @XmlEnumValue("South East")
    SOUTH_EAST("South East"),
    
    @XmlEnumValue("South West")
    SOUTH_WEST("South West"),
    
    @XmlEnumValue("Upper")
    UPPER("Upper"),
    
    @XmlEnumValue("West")
    WEST("West");
    private final String value;
    StreetSuffixList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static StreetSuffixList fromValue(String v) {
        for (StreetSuffixList c: StreetSuffixList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
