//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "streetTypeList")
@XmlEnum
public enum StreetTypeList {
    
    @XmlEnumValue("Access")
    ACCESS("Access"),
    
    @XmlEnumValue("Alley")
    ALLEY("Alley"),
    
    @XmlEnumValue("Alleyway")
    ALLEYWAY("Alleyway"),
    
    @XmlEnumValue("Amble")
    AMBLE("Amble"),
    
    @XmlEnumValue("Anchorage")
    ANCHORAGE("Anchorage"),
    
    @XmlEnumValue("Approach")
    APPROACH("Approach"),
    
    @XmlEnumValue("Arcade")
    ARCADE("Arcade"),
    
    @XmlEnumValue("Arterial")
    ARTERIAL("Arterial"),
    
    @XmlEnumValue("Artery")
    ARTERY("Artery"),
    
    @XmlEnumValue("Avenue")
    AVENUE("Avenue"),
    
    @XmlEnumValue("Banan")
    BANAN("Banan"),
    
    @XmlEnumValue("Bank")
    BANK("Bank"),
    
    @XmlEnumValue("Basin")
    BASIN("Basin"),
    
    @XmlEnumValue("Bay")
    BAY("Bay"),
    
    @XmlEnumValue("Beach")
    BEACH("Beach"),
    
    @XmlEnumValue("Bend")
    BEND("Bend"),
    
    @XmlEnumValue("Block")
    BLOCK("Block"),
    
    @XmlEnumValue("Boardwalk")
    BOARDWALK("Boardwalk"),
    
    @XmlEnumValue("Boulevard")
    BOULEVARD("Boulevard"),
    
    @XmlEnumValue("Boulevarde")
    BOULEVARDE("Boulevarde"),
    
    @XmlEnumValue("Bowl")
    BOWL("Bowl"),
    
    @XmlEnumValue("Brace")
    BRACE("Brace"),
    
    @XmlEnumValue("Brae")
    BRAE("Brae"),
    
    @XmlEnumValue("Break")
    BREAK("Break"),
    
    @XmlEnumValue("Bridge")
    BRIDGE("Bridge"),
    
    @XmlEnumValue("Broadway")
    BROADWAY("Broadway"),
    
    @XmlEnumValue("Brow")
    BROW("Brow"),
    
    @XmlEnumValue("Bypass")
    BYPASS("Bypass"),
    
    @XmlEnumValue("Byway")
    BYWAY("Byway"),
    
    @XmlEnumValue("Canal")
    CANAL("Canal"),
    
    @XmlEnumValue("Causeway")
    CAUSEWAY("Causeway"),
    
    @XmlEnumValue("Centre")
    CENTRE("Centre"),
    
    @XmlEnumValue("Centreway")
    CENTREWAY("Centreway"),
    
    @XmlEnumValue("Chase")
    CHASE("Chase"),
    
    @XmlEnumValue("Circle")
    CIRCLE("Circle"),
    
    @XmlEnumValue("Circlet")
    CIRCLET("Circlet"),
    
    @XmlEnumValue("Circuit")
    CIRCUIT("Circuit"),
    
    @XmlEnumValue("Circus")
    CIRCUS("Circus"),
    
    @XmlEnumValue("Close")
    CLOSE("Close"),
    
    @XmlEnumValue("Cluster")
    CLUSTER("Cluster"),
    
    @XmlEnumValue("Colonnade")
    COLONNADE("Colonnade"),
    
    @XmlEnumValue("Common")
    COMMON("Common"),
    
    @XmlEnumValue("Concourse")
    CONCOURSE("Concourse"),
    
    @XmlEnumValue("Connection")
    CONNECTION("Connection"),
    
    @XmlEnumValue("Copse")
    COPSE("Copse"),
    
    @XmlEnumValue("Corner")
    CORNER("Corner"),
    
    @XmlEnumValue("Corso")
    CORSO("Corso"),
    
    @XmlEnumValue("Course")
    COURSE("Course"),
    
    @XmlEnumValue("Court")
    COURT("Court"),
    
    @XmlEnumValue("Courtyard")
    COURTYARD("Courtyard"),
    
    @XmlEnumValue("Cove")
    COVE("Cove"),
    
    @XmlEnumValue("Crescent")
    CRESCENT("Crescent"),
    
    @XmlEnumValue("Crest")
    CREST("Crest"),
    
    @XmlEnumValue("Cross")
    CROSS("Cross"),
    
    @XmlEnumValue("Crossing")
    CROSSING("Crossing"),
    
    @XmlEnumValue("Crossroad")
    CROSSROAD("Crossroad"),
    
    @XmlEnumValue("Crossway")
    CROSSWAY("Crossway"),
    
    @XmlEnumValue("Cruiseway")
    CRUISEWAY("Cruiseway"),
    
    @XmlEnumValue("Cul-De-Sac")
    CUL_DE_SAC("Cul-De-Sac"),
    
    @XmlEnumValue("Cutting")
    CUTTING("Cutting"),
    
    @XmlEnumValue("Dale")
    DALE("Dale"),
    
    @XmlEnumValue("Dell")
    DELL("Dell"),
    
    @XmlEnumValue("Dene")
    DENE("Dene"),
    
    @XmlEnumValue("Deviation")
    DEVIATION("Deviation"),
    
    @XmlEnumValue("Dip")
    DIP("Dip"),
    
    @XmlEnumValue("Distributor")
    DISTRIBUTOR("Distributor"),
    
    @XmlEnumValue("Divide")
    DIVIDE("Divide"),
    
    @XmlEnumValue("Dock")
    DOCK("Dock"),
    
    @XmlEnumValue("Domain")
    DOMAIN("Domain"),
    
    @XmlEnumValue("Drive")
    DRIVE("Drive"),
    
    @XmlEnumValue("Driveway")
    DRIVEWAY("Driveway"),
    
    @XmlEnumValue("Edge")
    EDGE("Edge"),
    
    @XmlEnumValue("Elbow")
    ELBOW("Elbow"),
    
    @XmlEnumValue("End")
    END("End"),
    
    @XmlEnumValue("Entrance")
    ENTRANCE("Entrance"),
    
    @XmlEnumValue("Esplanade")
    ESPLANADE("Esplanade"),
    
    @XmlEnumValue("Estate")
    ESTATE("Estate"),
    
    @XmlEnumValue("Estuary")
    ESTUARY("Estuary"),
    
    @XmlEnumValue("Expressway")
    EXPRESSWAY("Expressway"),
    
    @XmlEnumValue("Extension")
    EXTENSION("Extension"),
    
    @XmlEnumValue("Fairway")
    FAIRWAY("Fairway"),
    
    @XmlEnumValue("Fire Track")
    FIRE_TRACK("Fire Track"),
    
    @XmlEnumValue("Firebreak")
    FIREBREAK("Firebreak"),
    
    @XmlEnumValue("Fireline")
    FIRELINE("Fireline"),
    
    @XmlEnumValue("Firetrack")
    FIRETRACK("Firetrack"),
    
    @XmlEnumValue("Firetrail")
    FIRETRAIL("Firetrail"),
    
    @XmlEnumValue("Flat")
    FLAT("Flat"),
    
    @XmlEnumValue("Follow")
    FOLLOW("Follow"),
    
    @XmlEnumValue("Footway")
    FOOTWAY("Footway"),
    
    @XmlEnumValue("Ford")
    FORD("Ford"),
    
    @XmlEnumValue("Foreshore")
    FORESHORE("Foreshore"),
    
    @XmlEnumValue("Formation")
    FORMATION("Formation"),
    
    @XmlEnumValue("Freeway")
    FREEWAY("Freeway"),
    
    @XmlEnumValue("Front")
    FRONT("Front"),
    
    @XmlEnumValue("Frontage")
    FRONTAGE("Frontage"),
    
    @XmlEnumValue("Gap")
    GAP("Gap"),
    
    @XmlEnumValue("Garden")
    GARDEN("Garden"),
    
    @XmlEnumValue("Gardens")
    GARDENS("Gardens"),
    
    @XmlEnumValue("Gate")
    GATE("Gate"),
    
    @XmlEnumValue("Gates")
    GATES("Gates"),
    
    @XmlEnumValue("Gateway")
    GATEWAY("Gateway"),
    
    @XmlEnumValue("Glade")
    GLADE("Glade"),
    
    @XmlEnumValue("Glen")
    GLEN("Glen"),
    
    @XmlEnumValue("Grange")
    GRANGE("Grange"),
    
    @XmlEnumValue("Green")
    GREEN("Green"),
    
    @XmlEnumValue("Ground")
    GROUND("Ground"),
    
    @XmlEnumValue("Grove")
    GROVE("Grove"),
    
    @XmlEnumValue("Gully")
    GULLY("Gully"),
    
    @XmlEnumValue("Harbour")
    HARBOUR("Harbour"),
    
    @XmlEnumValue("Heath")
    HEATH("Heath"),
    
    @XmlEnumValue("Heights")
    HEIGHTS("Heights"),
    
    @XmlEnumValue("Highroad")
    HIGHROAD("Highroad"),
    
    @XmlEnumValue("Highway")
    HIGHWAY("Highway"),
    
    @XmlEnumValue("Hill")
    HILL("Hill"),
    
    @XmlEnumValue("Hollow")
    HOLLOW("Hollow"),
    
    @XmlEnumValue("Hub")
    HUB("Hub"),
    
    @XmlEnumValue("Interchange")
    INTERCHANGE("Interchange"),
    
    @XmlEnumValue("Intersection")
    INTERSECTION("Intersection"),
    
    @XmlEnumValue("Junction")
    JUNCTION("Junction"),
    
    @XmlEnumValue("Key")
    KEY("Key"),
    
    @XmlEnumValue("Keys")
    KEYS("Keys"),
    
    @XmlEnumValue("Landing")
    LANDING("Landing"),
    
    @XmlEnumValue("Lane")
    LANE("Lane"),
    
    @XmlEnumValue("Laneway")
    LANEWAY("Laneway"),
    
    @XmlEnumValue("Lees")
    LEES("Lees"),
    
    @XmlEnumValue("Line")
    LINE("Line"),
    
    @XmlEnumValue("Link")
    LINK("Link"),
    
    @XmlEnumValue("Little")
    LITTLE("Little"),
    
    @XmlEnumValue("Lookout")
    LOOKOUT("Lookout"),
    
    @XmlEnumValue("Loop")
    LOOP("Loop"),
    
    @XmlEnumValue("Lower")
    LOWER("Lower"),
    
    @XmlEnumValue("Mall")
    MALL("Mall"),
    
    @XmlEnumValue("Manor")
    MANOR("Manor"),
    
    @XmlEnumValue("Meander")
    MEANDER("Meander"),
    
    @XmlEnumValue("Mears")
    MEARS("Mears"),
    
    @XmlEnumValue("Mew")
    MEW("Mew"),
    
    @XmlEnumValue("Mews")
    MEWS("Mews"),
    
    @XmlEnumValue("Mile")
    MILE("Mile"),
    
    @XmlEnumValue("Motorway")
    MOTORWAY("Motorway"),
    
    @XmlEnumValue("Mount")
    MOUNT("Mount"),
    
    @XmlEnumValue("Nook")
    NOOK("Nook"),
    
    @XmlEnumValue("Outlet")
    OUTLET("Outlet"),
    
    @XmlEnumValue("Outlook")
    OUTLOOK("Outlook"),
    
    @XmlEnumValue("Parade")
    PARADE("Parade"),
    
    @XmlEnumValue("Park")
    PARK("Park"),
    
    @XmlEnumValue("Parklands")
    PARKLANDS("Parklands"),
    
    @XmlEnumValue("Parkway")
    PARKWAY("Parkway"),
    
    @XmlEnumValue("Part")
    PART("Part"),
    
    @XmlEnumValue("Pass")
    PASS("Pass"),
    
    @XmlEnumValue("Path")
    PATH("Path"),
    
    @XmlEnumValue("Pathway")
    PATHWAY("Pathway"),
    
    @XmlEnumValue("Piazza")
    PIAZZA("Piazza"),
    
    @XmlEnumValue("Pier")
    PIER("Pier"),
    
    @XmlEnumValue("Place")
    PLACE("Place"),
    
    @XmlEnumValue("Plateau")
    PLATEAU("Plateau"),
    
    @XmlEnumValue("Plaza")
    PLAZA("Plaza"),
    
    @XmlEnumValue("Pocket")
    POCKET("Pocket"),
    
    @XmlEnumValue("Point")
    POINT("Point"),
    
    @XmlEnumValue("Port")
    PORT("Port"),
    
    @XmlEnumValue("Portal")
    PORTAL("Portal"),
    
    @XmlEnumValue("Promenade")
    PROMENADE("Promenade"),
    
    @XmlEnumValue("Pursuit")
    PURSUIT("Pursuit"),
    
    @XmlEnumValue("Quad")
    QUAD("Quad"),
    
    @XmlEnumValue("Quadrangle")
    QUADRANGLE("Quadrangle"),
    
    @XmlEnumValue("Quadrant")
    QUADRANT("Quadrant"),
    
    @XmlEnumValue("Quay")
    QUAY("Quay"),
    
    @XmlEnumValue("Quays")
    QUAYS("Quays"),
    
    @XmlEnumValue("Ramble")
    RAMBLE("Ramble"),
    
    @XmlEnumValue("Ramp")
    RAMP("Ramp"),
    
    @XmlEnumValue("Range")
    RANGE("Range"),
    
    @XmlEnumValue("Reach")
    REACH("Reach"),
    
    @XmlEnumValue("Reserve")
    RESERVE("Reserve"),
    
    @XmlEnumValue("Rest")
    REST("Rest"),
    
    @XmlEnumValue("Retreat")
    RETREAT("Retreat"),
    
    @XmlEnumValue("Return")
    RETURN("Return"),
    
    @XmlEnumValue("Ride")
    RIDE("Ride"),
    
    @XmlEnumValue("Ridge")
    RIDGE("Ridge"),
    
    @XmlEnumValue("Ridgeway")
    RIDGEWAY("Ridgeway"),
    
    @XmlEnumValue("Right Of Way")
    RIGHT_OF_WAY("Right Of Way"),
    
    @XmlEnumValue("Ring")
    RING("Ring"),
    
    @XmlEnumValue("Rise")
    RISE("Rise"),
    
    @XmlEnumValue("Rising")
    RISING("Rising"),
    
    @XmlEnumValue("River")
    RIVER("River"),
    
    @XmlEnumValue("Riverway")
    RIVERWAY("Riverway"),
    
    @XmlEnumValue("Riviera")
    RIVIERA("Riviera"),
    
    @XmlEnumValue("Road")
    ROAD("Road"),
    
    @XmlEnumValue("Roads")
    ROADS("Roads"),
    
    @XmlEnumValue("Roadside")
    ROADSIDE("Roadside"),
    
    @XmlEnumValue("Roadway")
    ROADWAY("Roadway"),
    
    @XmlEnumValue("Ronde")
    RONDE("Ronde"),
    
    @XmlEnumValue("Rosebowl")
    ROSEBOWL("Rosebowl"),
    
    @XmlEnumValue("Rotary")
    ROTARY("Rotary"),
    
    @XmlEnumValue("Round")
    ROUND("Round"),
    
    @XmlEnumValue("Route")
    ROUTE("Route"),
    
    @XmlEnumValue("Row")
    ROW("Row"),
    
    @XmlEnumValue("Rue")
    RUE("Rue"),
    
    @XmlEnumValue("Run")
    RUN("Run"),
    
    @XmlEnumValue("Service Way")
    SERVICE_WAY("Service Way"),
    
    @XmlEnumValue("Shunt")
    SHUNT("Shunt"),
    
    @XmlEnumValue("Siding")
    SIDING("Siding"),
    
    @XmlEnumValue("Slope")
    SLOPE("Slope"),
    
    @XmlEnumValue("Sound")
    SOUND("Sound"),
    
    @XmlEnumValue("Spur")
    SPUR("Spur"),
    
    @XmlEnumValue("Square")
    SQUARE("Square"),
    
    @XmlEnumValue("Stairs")
    STAIRS("Stairs"),
    
    @XmlEnumValue("State Highway")
    STATE_HIGHWAY("State Highway"),
    
    @XmlEnumValue("Steps")
    STEPS("Steps"),
    
    @XmlEnumValue("Strand")
    STRAND("Strand"),
    
    @XmlEnumValue("Street")
    STREET("Street"),
    
    @XmlEnumValue("Streets")
    STREETS("Streets"),
    
    @XmlEnumValue("Strip")
    STRIP("Strip"),
    
    @XmlEnumValue("Subway")
    SUBWAY("Subway"),
    
    @XmlEnumValue("Tarn")
    TARN("Tarn"),
    
    @XmlEnumValue("Tarnice Way")
    TARNICE_WAY("Tarnice Way"),
    
    @XmlEnumValue("Terrace")
    TERRACE("Terrace"),
    
    @XmlEnumValue("Thoroughfare")
    THOROUGHFARE("Thoroughfare"),
    
    @XmlEnumValue("Throughway")
    THROUGHWAY("Throughway"),
    
    @XmlEnumValue("Tollway")
    TOLLWAY("Tollway"),
    
    @XmlEnumValue("Top")
    TOP("Top"),
    
    @XmlEnumValue("Tor")
    TOR("Tor"),
    
    @XmlEnumValue("Towers")
    TOWERS("Towers"),
    
    @XmlEnumValue("Track")
    TRACK("Track"),
    
    @XmlEnumValue("Trail")
    TRAIL("Trail"),
    
    @XmlEnumValue("Trailer")
    TRAILER("Trailer"),
    
    @XmlEnumValue("Triangle")
    TRIANGLE("Triangle"),
    
    @XmlEnumValue("Trunkway")
    TRUNKWAY("Trunkway"),
    
    @XmlEnumValue("Turn")
    TURN("Turn"),
    
    @XmlEnumValue("Twist")
    TWIST("Twist"),
    
    @XmlEnumValue("Underpass")
    UNDERPASS("Underpass"),
    
    @XmlEnumValue("Upper")
    UPPER("Upper"),
    
    @XmlEnumValue("Vale")
    VALE("Vale"),
    
    @XmlEnumValue("Viaduct")
    VIADUCT("Viaduct"),
    
    @XmlEnumValue("View")
    VIEW("View"),
    
    @XmlEnumValue("Villas")
    VILLAS("Villas"),
    
    @XmlEnumValue("Vista")
    VISTA("Vista"),
    
    @XmlEnumValue("Wade")
    WADE("Wade"),
    
    @XmlEnumValue("Walk")
    WALK("Walk"),
    
    @XmlEnumValue("Walkway")
    WALKWAY("Walkway"),
    
    @XmlEnumValue("Waterway")
    WATERWAY("Waterway"),
    
    @XmlEnumValue("Way")
    WAY("Way"),
    
    @XmlEnumValue("Wharf")
    WHARF("Wharf"),
    
    @XmlEnumValue("Woods")
    WOODS("Woods"),
    
    @XmlEnumValue("Wynd")
    WYND("Wynd"),
    
    @XmlEnumValue("Yard")
    YARD("Yard");
    private final String value;
    StreetTypeList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static StreetTypeList fromValue(String v) {
        for (StreetTypeList c: StreetTypeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
