//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "surplusFundsDisbursementMethodList")
@XmlEnum
public enum SurplusFundsDisbursementMethodList {
    
    @XmlEnumValue("Bank Cheque")
    BANK_CHEQUE("Bank Cheque"),
    
    @XmlEnumValue("Bpay")
    BPAY("Bpay"),
    
    @XmlEnumValue("Existing Direct Debit Account")
    EXISTING_DIRECT_DEBIT_ACCOUNT("Existing Direct Debit Account"),
    
    @XmlEnumValue("Existing Other Account")
    EXISTING_OTHER_ACCOUNT("Existing Other Account"),
    
    @XmlEnumValue("New Account")
    NEW_ACCOUNT("New Account"),
    
    @XmlEnumValue("Redraw")
    REDRAW("Redraw");
    private final String value;
    SurplusFundsDisbursementMethodList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static SurplusFundsDisbursementMethodList fromValue(String v) {
        for (SurplusFundsDisbursementMethodList c: SurplusFundsDisbursementMethodList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
