//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "taxDeclarationExemptionCategoryList")
@XmlEnum
public enum TaxDeclarationExemptionCategoryList {
    
    @XmlEnumValue("Age Pension")
    AGE_PENSION("Age Pension"),
    
    @XmlEnumValue("Carer Payment")
    CARER_PAYMENT("Carer Payment"),
    
    @XmlEnumValue("Child Exemption")
    CHILD_EXEMPTION("Child Exemption"),
    
    @XmlEnumValue("Disability Support Pension")
    DISABILITY_SUPPORT_PENSION("Disability Support Pension"),
    
    @XmlEnumValue("Non-Resident Exemption")
    NON_RESIDENT_EXEMPTION("Non-Resident Exemption"),
    
    @XmlEnumValue("Not Required for Interest Income")
    NOT_REQUIRED_FOR_INTEREST_INCOME("Not Required for Interest Income"),
    
    @XmlEnumValue("Not Required to Lodge a Tax Return")
    NOT_REQUIRED_TO_LODGE_A_TAX_RETURN("Not Required to Lodge a Tax Return"),
    
    @XmlEnumValue("Parenting Payment Single")
    PARENTING_PAYMENT_SINGLE("Parenting Payment Single"),
    
    @XmlEnumValue("Special Benefit")
    SPECIAL_BENEFIT("Special Benefit"),
    
    @XmlEnumValue("Special Needs Pension")
    SPECIAL_NEEDS_PENSION("Special Needs Pension"),
    
    @XmlEnumValue("Veteran Allowance")
    VETERAN_ALLOWANCE("Veteran Allowance"),
    
    @XmlEnumValue("Veteran Pension")
    VETERAN_PENSION("Veteran Pension"),
    
    @XmlEnumValue("Widow B Pension")
    WIDOW_B_PENSION("Widow B Pension"),
    
    @XmlEnumValue("Wife Pension")
    WIFE_PENSION("Wife Pension");
    private final String value;
    TaxDeclarationExemptionCategoryList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static TaxDeclarationExemptionCategoryList fromValue(String v) {
        for (TaxDeclarationExemptionCategoryList c: TaxDeclarationExemptionCategoryList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
