//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "tinNotProvidedReasonList")
@XmlEnum
public enum TinNotProvidedReasonList {
    
    @XmlEnumValue("Country of Tax Association Does Not Issue a TIN")
    COUNTRY_OF_TAX_ASSOCIATION_DOES_NOT_ISSUE_A_TIN("Country of Tax Association Does Not Issue a TIN"),
    
    @XmlEnumValue("Country of Tax Association Does Not Require TIN to Be Disclosed")
    COUNTRY_OF_TAX_ASSOCIATION_DOES_NOT_REQUIRE_TIN_TO_BE_DISCLOSED("Country of Tax Association Does Not Require TIN to Be Disclosed"),
    
    @XmlEnumValue("Entity Is Otherwise Unable to Obtain a TIN or Equivalent Number")
    ENTITY_IS_OTHERWISE_UNABLE_TO_OBTAIN_A_TIN_OR_EQUIVALENT_NUMBER("Entity Is Otherwise Unable to Obtain a TIN or Equivalent Number");
    private final String value;
    TinNotProvidedReasonList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static TinNotProvidedReasonList fromValue(String v) {
        for (TinNotProvidedReasonList c: TinNotProvidedReasonList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
