//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "toolsOfTradeTypeList")
@XmlEnum
public enum ToolsOfTradeTypeList {
    
    @XmlEnumValue("Camera")
    CAMERA("Camera"),
    
    @XmlEnumValue("Other")
    OTHER("Other"),
    
    @XmlEnumValue("Power Tools")
    POWER_TOOLS("Power Tools"),
    
    @XmlEnumValue("Surveying Equipment")
    SURVEYING_EQUIPMENT("Surveying Equipment"),
    
    @XmlEnumValue("Tools - Laser Beam")
    TOOLS_LASER_BEAM("Tools - Laser Beam"),
    
    @XmlEnumValue("Tools General")
    TOOLS_GENERAL("Tools General");
    private final String value;
    ToolsOfTradeTypeList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static ToolsOfTradeTypeList fromValue(String v) {
        for (ToolsOfTradeTypeList c: ToolsOfTradeTypeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
