//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "unitTypeList")
@XmlEnum
public enum UnitTypeList {
    
    @XmlEnumValue("Antenna")
    ANTENNA("Antenna"),
    
    @XmlEnumValue("Apartment")
    APARTMENT("Apartment"),
    
    @XmlEnumValue("Automated Teller Machine")
    AUTOMATED_TELLER_MACHINE("Automated Teller Machine"),
    
    @XmlEnumValue("Automatic Teller")
    AUTOMATIC_TELLER("Automatic Teller"),
    
    @XmlEnumValue("Barbecue")
    BARBECUE("Barbecue"),
    
    @XmlEnumValue("Boatshed")
    BOATSHED("Boatshed"),
    
    @XmlEnumValue("Building")
    BUILDING("Building"),
    
    @XmlEnumValue("Bungalow")
    BUNGALOW("Bungalow"),
    
    @XmlEnumValue("Cage")
    CAGE("Cage"),
    
    @XmlEnumValue("Carpark")
    CARPARK("Carpark"),
    
    @XmlEnumValue("Carspace")
    CARSPACE("Carspace"),
    
    @XmlEnumValue("Club")
    CLUB("Club"),
    
    @XmlEnumValue("Condominium")
    CONDOMINIUM("Condominium"),
    
    @XmlEnumValue("Coolroom")
    COOLROOM("Coolroom"),
    
    @XmlEnumValue("Cottage")
    COTTAGE("Cottage"),
    
    @XmlEnumValue("Duplex")
    DUPLEX("Duplex"),
    
    @XmlEnumValue("Factory")
    FACTORY("Factory"),
    
    @XmlEnumValue("Flat")
    FLAT("Flat"),
    
    @XmlEnumValue("Garage")
    GARAGE("Garage"),
    
    @XmlEnumValue("Hall")
    HALL("Hall"),
    
    @XmlEnumValue("House")
    HOUSE("House"),
    
    @XmlEnumValue("Kiosk")
    KIOSK("Kiosk"),
    
    @XmlEnumValue("Lease")
    LEASE("Lease"),
    
    @XmlEnumValue("Lobby")
    LOBBY("Lobby"),
    
    @XmlEnumValue("Loft")
    LOFT("Loft"),
    
    @XmlEnumValue("Lot")
    LOT("Lot"),
    
    @XmlEnumValue("Maisonette")
    MAISONETTE("Maisonette"),
    
    @XmlEnumValue("Marine Berth")
    MARINE_BERTH("Marine Berth"),
    
    @XmlEnumValue("Office")
    OFFICE("Office"),
    
    @XmlEnumValue("Penthouse")
    PENTHOUSE("Penthouse"),
    
    @XmlEnumValue("Reserve")
    RESERVE("Reserve"),
    
    @XmlEnumValue("Room")
    ROOM("Room"),
    
    @XmlEnumValue("Shed")
    SHED("Shed"),
    
    @XmlEnumValue("Shop")
    SHOP("Shop"),
    
    @XmlEnumValue("Showroom")
    SHOWROOM("Showroom"),
    
    @XmlEnumValue("Sign")
    SIGN("Sign"),
    
    @XmlEnumValue("Site")
    SITE("Site"),
    
    @XmlEnumValue("Stall")
    STALL("Stall"),
    
    @XmlEnumValue("Store")
    STORE("Store"),
    
    @XmlEnumValue("Strata Unit")
    STRATA_UNIT("Strata Unit"),
    
    @XmlEnumValue("Studio / Studio Apartment")
    STUDIO_STUDIO_APARTMENT("Studio / Studio Apartment"),
    
    @XmlEnumValue("Substation")
    SUBSTATION("Substation"),
    
    @XmlEnumValue("Suite")
    SUITE("Suite"),
    
    @XmlEnumValue("Tenancy")
    TENANCY("Tenancy"),
    
    @XmlEnumValue("Tower")
    TOWER("Tower"),
    
    @XmlEnumValue("Townhouse")
    TOWNHOUSE("Townhouse"),
    
    @XmlEnumValue("Unit")
    UNIT("Unit"),
    
    @XmlEnumValue("Vault")
    VAULT("Vault"),
    
    @XmlEnumValue("Villa")
    VILLA("Villa"),
    
    @XmlEnumValue("Ward")
    WARD("Ward"),
    
    @XmlEnumValue("Warehouse")
    WAREHOUSE("Warehouse"),
    
    @XmlEnumValue("Workshop")
    WORKSHOP("Workshop");
    private final String value;
    UnitTypeList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static UnitTypeList fromValue(String v) {
        for (UnitTypeList c: UnitTypeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
