//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "valuationProgramList")
@XmlEnum
public enum ValuationProgramList {
    
    AVM("AVM"),
    
    @XmlEnumValue("Costing")
    COSTING("Costing"),
    
    @XmlEnumValue("Desktop")
    DESKTOP("Desktop"),
    
    @XmlEnumValue("Full Registered")
    FULL_REGISTERED("Full Registered"),
    
    @XmlEnumValue("Kerb Side")
    KERB_SIDE("Kerb Side"),
    
    @XmlEnumValue("None")
    NONE("None"),
    
    @XmlEnumValue("Progress Inspection")
    PROGRESS_INSPECTION("Progress Inspection");
    private final String value;
    ValuationProgramList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static ValuationProgramList fromValue(String v) {
        for (ValuationProgramList c: ValuationProgramList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
