//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "variationTypeList")
@XmlEnum
public enum VariationTypeList {
    
    @XmlEnumValue("Add Borrower")
    ADD_BORROWER("Add Borrower"),
    
    @XmlEnumValue("Add Guarantee")
    ADD_GUARANTEE("Add Guarantee"),
    
    @XmlEnumValue("Add Guarantee Security")
    ADD_GUARANTEE_SECURITY("Add Guarantee Security"),
    
    @XmlEnumValue("Add Guarantor")
    ADD_GUARANTOR("Add Guarantor"),
    
    @XmlEnumValue("Add Security")
    ADD_SECURITY("Add Security"),
    
    @XmlEnumValue("Balance Increase")
    BALANCE_INCREASE("Balance Increase"),
    
    @XmlEnumValue("Change Loan Term")
    CHANGE_LOAN_TERM("Change Loan Term"),
    
    @XmlEnumValue("Change Repayment Amount")
    CHANGE_REPAYMENT_AMOUNT("Change Repayment Amount"),
    
    @XmlEnumValue("Change Repayment Frequency")
    CHANGE_REPAYMENT_FREQUENCY("Change Repayment Frequency"),
    
    @XmlEnumValue("Change Repayment Type")
    CHANGE_REPAYMENT_TYPE("Change Repayment Type"),
    
    @XmlEnumValue("Close Account")
    CLOSE_ACCOUNT("Close Account"),
    
    @XmlEnumValue("Interest Rate Discount")
    INTEREST_RATE_DISCOUNT("Interest Rate Discount"),
    
    @XmlEnumValue("Lending Guarantee Limit Decrease")
    LENDING_GUARANTEE_LIMIT_DECREASE("Lending Guarantee Limit Decrease"),
    
    @XmlEnumValue("Lending Guarantee Limit Increase")
    LENDING_GUARANTEE_LIMIT_INCREASE("Lending Guarantee Limit Increase"),
    
    @XmlEnumValue("Limit Increase")
    LIMIT_INCREASE("Limit Increase"),
    
    @XmlEnumValue("Reduce Balance")
    REDUCE_BALANCE("Reduce Balance"),
    
    @XmlEnumValue("Reduce Limit")
    REDUCE_LIMIT("Reduce Limit"),
    
    @XmlEnumValue("Release Guarantee")
    RELEASE_GUARANTEE("Release Guarantee"),
    
    @XmlEnumValue("Release Guarantee Security")
    RELEASE_GUARANTEE_SECURITY("Release Guarantee Security"),
    
    @XmlEnumValue("Release Guarantor")
    RELEASE_GUARANTOR("Release Guarantor"),
    
    @XmlEnumValue("Release Security")
    RELEASE_SECURITY("Release Security"),
    
    @XmlEnumValue("Remove Borrower")
    REMOVE_BORROWER("Remove Borrower"),
    
    @XmlEnumValue("Split Account")
    SPLIT_ACCOUNT("Split Account"),
    
    @XmlEnumValue("Substitute Guarantee Security")
    SUBSTITUTE_GUARANTEE_SECURITY("Substitute Guarantee Security"),
    
    @XmlEnumValue("Substitute Security")
    SUBSTITUTE_SECURITY("Substitute Security"),
    
    @XmlEnumValue("Switch Product")
    SWITCH_PRODUCT("Switch Product"),
    
    @XmlEnumValue("Update Party Details")
    UPDATE_PARTY_DETAILS("Update Party Details");
    private final String value;
    VariationTypeList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static VariationTypeList fromValue(String v) {
        for (VariationTypeList c: VariationTypeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
