//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "varyOnValuationList")
@XmlEnum
public enum VaryOnValuationList {
    
    @XmlEnumValue("Cash Reserve")
    CASH_RESERVE("Cash Reserve"),
    
    @XmlEnumValue("Instalments")
    INSTALMENTS("Instalments"),
    
    @XmlEnumValue("Lump Sum")
    LUMP_SUM("Lump Sum");
    private final String value;
    VaryOnValuationList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static VaryOnValuationList fromValue(String v) {
        for (VaryOnValuationList c: VaryOnValuationList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
