//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;
@XmlType(name = "vehicleTypeList")
@XmlEnum
public enum VehicleTypeList {
    
    @XmlEnumValue("Bicycle")
    BICYCLE("Bicycle"),
    
    @XmlEnumValue("Bodies")
    BODIES("Bodies"),
    
    @XmlEnumValue("Bus Coach or Special Purpose")
    BUS_COACH_OR_SPECIAL_PURPOSE("Bus Coach or Special Purpose"),
    
    @XmlEnumValue("Car")
    CAR("Car"),
    
    @XmlEnumValue("Caravan")
    CARAVAN("Caravan"),
    
    @XmlEnumValue("Light Commercial")
    LIGHT_COMMERCIAL("Light Commercial"),
    
    @XmlEnumValue("Locomotive")
    LOCOMOTIVE("Locomotive"),
    
    @XmlEnumValue("Motorcycle")
    MOTORCYCLE("Motorcycle"),
    
    @XmlEnumValue("Other")
    OTHER("Other"),
    
    @XmlEnumValue("Rail Cars")
    RAIL_CARS("Rail Cars"),
    
    @XmlEnumValue("Trailer")
    TRAILER("Trailer"),
    
    @XmlEnumValue("Truck")
    TRUCK("Truck"),
    
    @XmlEnumValue("Watercraft")
    WATERCRAFT("Watercraft");
    private final String value;
    VehicleTypeList(String v) {
        value = v;
    }
    public String value() {
        return value;
    }
    public static VehicleTypeList fromValue(String v) {
        for (VehicleTypeList c: VehicleTypeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
