//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "vendorTaxInvoiceType", propOrder = {
    "asset"
})
public class VendorTaxInvoiceType {
    @XmlElement(name = "Asset")
    protected List<VendorTaxInvoiceType.Asset> asset;
    @XmlAttribute(name = "InvoiceNumber")
    protected String invoiceNumber;
    @XmlAttribute(name = "TaxInvoiceDate")
    protected XMLGregorianCalendar taxInvoiceDate;
    @XmlAttribute(name = "UniqueID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String uniqueID;
    @XmlAttribute(name = "x_DeliverTo")
    @XmlIDREF
    protected Object xDeliverTo;
    @XmlAttribute(name = "x_Purchaser")
    @XmlIDREF
    protected Object xPurchaser;
    @XmlAttribute(name = "x_Vendor")
    @XmlIDREF
    protected Object xVendor;
    
    public List<VendorTaxInvoiceType.Asset> getAsset() {
        if (asset == null) {
            asset = new ArrayList<VendorTaxInvoiceType.Asset>();
        }
        return this.asset;
    }
    
    public String getInvoiceNumber() {
        return invoiceNumber;
    }
    
    public void setInvoiceNumber(String value) {
        this.invoiceNumber = value;
    }
    
    public XMLGregorianCalendar getTaxInvoiceDate() {
        return taxInvoiceDate;
    }
    
    public void setTaxInvoiceDate(XMLGregorianCalendar value) {
        this.taxInvoiceDate = value;
    }
    
    public String getUniqueID() {
        return uniqueID;
    }
    
    public void setUniqueID(String value) {
        this.uniqueID = value;
    }
    
    public Object getXDeliverTo() {
        return xDeliverTo;
    }
    
    public void setXDeliverTo(Object value) {
        this.xDeliverTo = value;
    }
    
    public Object getXPurchaser() {
        return xPurchaser;
    }
    
    public void setXPurchaser(Object value) {
        this.xPurchaser = value;
    }
    
    public Object getXVendor() {
        return xVendor;
    }
    
    public void setXVendor(Object value) {
        this.xVendor = value;
    }
    
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Asset {
        @XmlAttribute(name = "AssetDescription")
        protected String assetDescription;
        @XmlAttribute(name = "DeliveryDate")
        protected XMLGregorianCalendar deliveryDate;
        @XmlAttribute(name = "DepositPaid")
        protected BigDecimal depositPaid;
        @XmlAttribute(name = "FinalPosition")
        protected BigDecimal finalPosition;
        @XmlAttribute(name = "GoodsDelivery")
        protected GoodsDeliveryList goodsDelivery;
        @XmlAttribute(name = "GSTComponent")
        protected BigDecimal gstComponent;
        @XmlAttribute(name = "NonTaxableAmount")
        protected BigDecimal nonTaxableAmount;
        @XmlAttribute(name = "OnCosts")
        protected BigDecimal onCosts;
        @XmlAttribute(name = "Payout")
        protected BigDecimal payout;
        @XmlAttribute(name = "Refund")
        protected BigDecimal refund;
        @XmlAttribute(name = "TaxableAmountOfAsset")
        protected BigDecimal taxableAmountOfAsset;
        @XmlAttribute(name = "TotalCostOfAsset")
        protected BigDecimal totalCostOfAsset;
        @XmlAttribute(name = "TradeIn")
        protected BigDecimal tradeIn;
        @XmlAttribute(name = "UniqueAssetIdentifier")
        protected String uniqueAssetIdentifier;
        
        public String getAssetDescription() {
            return assetDescription;
        }
        
        public void setAssetDescription(String value) {
            this.assetDescription = value;
        }
        
        public XMLGregorianCalendar getDeliveryDate() {
            return deliveryDate;
        }
        
        public void setDeliveryDate(XMLGregorianCalendar value) {
            this.deliveryDate = value;
        }
        
        public BigDecimal getDepositPaid() {
            return depositPaid;
        }
        
        public void setDepositPaid(BigDecimal value) {
            this.depositPaid = value;
        }
        
        public BigDecimal getFinalPosition() {
            return finalPosition;
        }
        
        public void setFinalPosition(BigDecimal value) {
            this.finalPosition = value;
        }
        
        public GoodsDeliveryList getGoodsDelivery() {
            return goodsDelivery;
        }
        
        public void setGoodsDelivery(GoodsDeliveryList value) {
            this.goodsDelivery = value;
        }
        
        public BigDecimal getGSTComponent() {
            return gstComponent;
        }
        
        public void setGSTComponent(BigDecimal value) {
            this.gstComponent = value;
        }
        
        public BigDecimal getNonTaxableAmount() {
            return nonTaxableAmount;
        }
        
        public void setNonTaxableAmount(BigDecimal value) {
            this.nonTaxableAmount = value;
        }
        
        public BigDecimal getOnCosts() {
            return onCosts;
        }
        
        public void setOnCosts(BigDecimal value) {
            this.onCosts = value;
        }
        
        public BigDecimal getPayout() {
            return payout;
        }
        
        public void setPayout(BigDecimal value) {
            this.payout = value;
        }
        
        public BigDecimal getRefund() {
            return refund;
        }
        
        public void setRefund(BigDecimal value) {
            this.refund = value;
        }
        
        public BigDecimal getTaxableAmountOfAsset() {
            return taxableAmountOfAsset;
        }
        
        public void setTaxableAmountOfAsset(BigDecimal value) {
            this.taxableAmountOfAsset = value;
        }
        
        public BigDecimal getTotalCostOfAsset() {
            return totalCostOfAsset;
        }
        
        public void setTotalCostOfAsset(BigDecimal value) {
            this.totalCostOfAsset = value;
        }
        
        public BigDecimal getTradeIn() {
            return tradeIn;
        }
        
        public void setTradeIn(BigDecimal value) {
            this.tradeIn = value;
        }
        
        public String getUniqueAssetIdentifier() {
            return uniqueAssetIdentifier;
        }
        
        public void setUniqueAssetIdentifier(String value) {
            this.uniqueAssetIdentifier = value;
        }
    }
}
