//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import lombok.Data;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "foreignTaxAssociationType", propOrder = {
    "detail"
})

@Data

@Entity
public class ForeignTaxAssociationType {
    @XmlElement(name = "Detail")
    protected List<ForeignTaxAssociationType.Detail> detail;
    @XmlAttribute(name = "SelfCertificationDeclaration")
    protected YesNoList selfCertificationDeclaration;
    @XmlAttribute(name = "Status")
    protected ForeignTaxAssociationStatusList status;
    public List<ForeignTaxAssociationType.Detail> getDetail() {
        if (detail == null) {
            detail = new ArrayList<ForeignTaxAssociationType.Detail>();
        }
        return this.detail;
    }
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")

@Data

@Entity
    public static class Detail {
        @XmlAttribute(name = "Country")
        protected CountryCodeList country;
        @XmlAttribute(name = "Status")
        protected ForeignTaxAssociationStatusList status;
        @XmlAttribute(name = "TaxIdentificationNumber")
        protected String taxIdentificationNumber;
        @XmlAttribute(name = "TINNotProvidedReason")
        protected TinNotProvidedReasonList tinNotProvidedReason;
        @XmlAttribute(name = "TINNotProvidedReasonDetail")
        protected String tinNotProvidedReasonDetail;
    }
}
