//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import lombok.Data;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "responsibleLendingType", propOrder = {
    "mitigant",
    "significantChange"
})

@Data

@Entity
public class ResponsibleLendingType {
    @XmlElement(name = "Mitigant")
    protected List<ResponsibleLendingType.Mitigant> mitigant;
    @XmlElement(name = "SignificantChange")
    protected List<ResponsibleLendingType.SignificantChange> significantChange;
    @XmlAttribute(name = "AnticipatedChanges")
    protected YesNoList anticipatedChanges;
    public List<ResponsibleLendingType.Mitigant> getMitigant() {
        if (mitigant == null) {
            mitigant = new ArrayList<ResponsibleLendingType.Mitigant>();
        }
        return this.mitigant;
    }
    public List<ResponsibleLendingType.SignificantChange> getSignificantChange() {
        if (significantChange == null) {
            significantChange = new ArrayList<ResponsibleLendingType.SignificantChange>();
        }
        return this.significantChange;
    }
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "saleOfAssets",
        "savingsOrSuperannuation"
    })

@Data

@Entity
    public static class Mitigant {
        @XmlElement(name = "SaleOfAssets")
        protected ResponsibleLendingType.Mitigant.SaleOfAssets saleOfAssets;
        @XmlElement(name = "SavingsOrSuperannuation")
        protected ResponsibleLendingType.Mitigant.SavingsOrSuperannuation savingsOrSuperannuation;
        @XmlAttribute(name = "Description")
        protected String description;
        @XmlAttribute(name = "Factor")
        protected MitigantFactorList factor;
        @XmlAttribute(name = "UniqueID")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlID
        protected String uniqueID;
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")

@Data

@Entity
        public static class SaleOfAssets {
            @XmlAttribute(name = "LenderHeldSecurity")
            protected YesNoList lenderHeldSecurity;
            @XmlAttribute(name = "LenderHeldSecurityDescription")
            protected String lenderHeldSecurityDescription;
            @XmlAttribute(name = "OtherAssets")
            protected YesNoList otherAssets;
            @XmlAttribute(name = "OtherAssetsDescription")
            protected String otherAssetsDescription;
            @XmlAttribute(name = "OtherLenderHeldSecurity")
            protected YesNoList otherLenderHeldSecurity;
            @XmlAttribute(name = "OtherLenderHeldSecurityDescription")
            protected String otherLenderHeldSecurityDescription;
            @XmlAttribute(name = "Shares")
            protected YesNoList shares;
            @XmlAttribute(name = "SharesDescription")
            protected String sharesDescription;
        }
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")

@Data

@Entity
        public static class SavingsOrSuperannuation {
            @XmlAttribute(name = "LenderHeldSavingsAccount")
            protected YesNoList lenderHeldSavingsAccount;
            @XmlAttribute(name = "LenderHeldSavingsAccountDescription")
            protected String lenderHeldSavingsAccountDescription;
            @XmlAttribute(name = "OtherLenderHeldSavingsAccount")
            protected YesNoList otherLenderHeldSavingsAccount;
            @XmlAttribute(name = "OtherLenderHeldSavingsAccountDescription")
            protected String otherLenderHeldSavingsAccountDescription;
        }
    }
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")

@Data

@Entity
    public static class SignificantChange {
        @XmlAttribute(name = "Change")
        protected SignificantChangeList change;
        @XmlAttribute(name = "Description")
        protected String description;
        @XmlAttribute(name = "EndDate")
        protected XMLGregorianCalendar endDate;
        @XmlAttribute(name = "MonthlyFinancialImpact")
        protected BigDecimal monthlyFinancialImpact;
        @XmlAttribute(name = "StartDate")
        protected XMLGregorianCalendar startDate;
        @XmlAttribute(name = "UniqueID")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlID
        protected String uniqueID;
    }
}
