//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import lombok.Data;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "signatureType", propOrder = {
    "capacity",
    "contact"
})

@Data

@Entity
public class SignatureType {
    @XmlElement(name = "Capacity")
    protected SignatureType.Capacity capacity;
    @XmlElement(name = "Contact")
    protected SignatureType.Contact contact;
    @XmlAttribute(name = "Date")
    protected XMLGregorianCalendar date;
    @XmlAttribute(name = "ElectronicSignature")
    protected YesNoList electronicSignature;
    @XmlAttribute(name = "Rank")
    protected BigInteger rank;
    @XmlAttribute(name = "UniqueID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String uniqueID;
    @XmlAttribute(name = "x_Signatory")
    @XmlIDREF
    protected Object xSignatory;
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")

@Data

@Entity
    public static class Capacity {
        @XmlAttribute(name = "Type")
        protected CapacityTypeList type;
        @XmlAttribute(name = "x_ParentEntity")
        @XmlIDREF
        protected Object xParentEntity;
        @XmlAttribute(name = "x_ProductSet")
        @XmlIDREF
        protected Object xProductSet;
    }
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "mobile"
    })

@Data

@Entity
    public static class Contact {
        @XmlElement(name = "Mobile")
        protected PhoneType mobile;
        @XmlAttribute(name = "Email")
        protected String email;
    }
}
