//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.20 at 10:22:11 PM AWST 
//
package com.moneycatcha.app.model;
import lombok.Data;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "vendorTaxInvoiceType", propOrder = {
    "asset"
})

@Data

@Entity
public class VendorTaxInvoiceType {
    @XmlElement(name = "Asset")
    protected List<VendorTaxInvoiceType.Asset> asset;
    @XmlAttribute(name = "InvoiceNumber")
    protected String invoiceNumber;
    @XmlAttribute(name = "TaxInvoiceDate")
    protected XMLGregorianCalendar taxInvoiceDate;
    @XmlAttribute(name = "UniqueID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String uniqueID;
    @XmlAttribute(name = "x_DeliverTo")
    @XmlIDREF
    protected Object xDeliverTo;
    @XmlAttribute(name = "x_Purchaser")
    @XmlIDREF
    protected Object xPurchaser;
    @XmlAttribute(name = "x_Vendor")
    @XmlIDREF
    protected Object xVendor;
    public List<VendorTaxInvoiceType.Asset> getAsset() {
        if (asset == null) {
            asset = new ArrayList<VendorTaxInvoiceType.Asset>();
        }
        return this.asset;
    }
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")

@Data

@Entity
    public static class Asset {
        @XmlAttribute(name = "AssetDescription")
        protected String assetDescription;
        @XmlAttribute(name = "DeliveryDate")
        protected XMLGregorianCalendar deliveryDate;
        @XmlAttribute(name = "DepositPaid")
        protected BigDecimal depositPaid;
        @XmlAttribute(name = "FinalPosition")
        protected BigDecimal finalPosition;
        @XmlAttribute(name = "GoodsDelivery")
        protected GoodsDeliveryList goodsDelivery;
        @XmlAttribute(name = "GSTComponent")
        protected BigDecimal gstComponent;
        @XmlAttribute(name = "NonTaxableAmount")
        protected BigDecimal nonTaxableAmount;
        @XmlAttribute(name = "OnCosts")
        protected BigDecimal onCosts;
        @XmlAttribute(name = "Payout")
        protected BigDecimal payout;
        @XmlAttribute(name = "Refund")
        protected BigDecimal refund;
        @XmlAttribute(name = "TaxableAmountOfAsset")
        protected BigDecimal taxableAmountOfAsset;
        @XmlAttribute(name = "TotalCostOfAsset")
        protected BigDecimal totalCostOfAsset;
        @XmlAttribute(name = "TradeIn")
        protected BigDecimal tradeIn;
        @XmlAttribute(name = "UniqueAssetIdentifier")
        protected String uniqueAssetIdentifier;
    }
}
